### ISSUE TITLE
添加TCGA分子亚型数据

### ISSUE THREAD

**Issue by Byronxy** [openbiox/UCSCXenaShiny#101]
考虑打包来自TCGAbiolinks包的数据，参考https://bioinformaticsfmrp.github.io/TCGAbiolinks/subtypes.html
@ShixiangWang

**Comment by ShixiangWang** [comment]
你要打包这个数据的目的是什么？然后这个数据是怎么来的，一般而言，xena都有

**Comment by Byronxy** [comment]
> 你要打包这个数据的目的是什么？然后这个数据是怎么来的，一般而言，xena都有

后续分析的时候可以考虑纳入分子亚型的信息。我之前自己做分析的时候，发现这部分数据是xena是没有或者不完善的。这个数据来源是一些已发表文献的补充材料，这里写清楚了。我自己后续还有个想法就是可以像TCGAbiolinks包一样，写一些文档，从数据下载到数据分析，所以我觉得这个数据可以打包，预备在这里
![image](https://user-images.githubusercontent.com/28949856/87242752-1cf6d900-c462-11ea-9b30-cf5f01aba064.png)

**Comment by ShixiangWang** [comment]
@Byronxy 目前我们的包已经比较大了，这对下载者是一个严重的负担，后续可以还需要尽量清理掉保存的大的数据集，包内只保留让核心功能发挥作用的数据。我的想法是把这类预处理好的（非Xena非核心）的数据统一进行存放，有需要时再下载下来，我创建了一个仓库 https://gitee.com/XenaShiny/XenaExtraDataHub 你可以考虑把数据加到里面。如果你同意这一点，可以创建一个 gitee 帐号，我把你加进去。

**Comment by Byronxy** [comment]
> @Byronxy 目前我们的包已经比较大了，这对下载者是一个严重的负担，后续可以还需要尽量清理掉保存的大的数据集，包内只保留让核心功能发挥作用的数据。我的想法是把这类预处理好的（非Xena非核心）的数据统一进行存放，有需要时再下载下来，我创建了一个仓库 https://gitee.com/XenaShiny/XenaExtraDataHub 你可以考虑把数据加到里面。如果你同意这一点，可以创建一个 gitee 帐号，我把你加进去。

可以，我的账号就是yi__xiong

**Comment by ShixiangWang** [comment]
@Byronxy 我给你发邀请链接了

**Comment by ShixiangWang** [comment]
你看下下面这两个数据集，应该跟你最上面链接的数据源是一致的

- https://xenabrowser.net/datapages/?dataset=TCGASubtype.20170308.tsv&host=https%3A%2F%2Fpancanatlas.xenahubs.net&removeHub=https%3A%2F%2Fxena.treehouse.gi.ucsc.edu%3A443
- https://xenabrowser.net/datapages/?dataset=Subtype_Immune_Model_Based.txt&host=https%3A%2F%2Fpancanatlas.xenahubs.net&removeHub=https%3A%2F%2Fxena.treehouse.gi.ucsc.edu%3A443

**Comment by ShixiangWang** [comment]
这个数据集有打包进包里吗？

**Comment by ShixiangWang** [comment]
@Byronxy

**Comment by Byronxy** [comment]
> @Byronxy

没有

**Comment by ShixiangWang** [comment]
/remind me to add the subtype datasets in 3 days.
