### ISSUE TITLE
CCLE 泛癌基因表达

### ISSUE THREAD

**Issue by ShixiangWang** [openbiox/UCSCXenaShiny#118]
@Byronxy 目前已经能够获取 CCLE 表达数据，能否直接泛癌表达模块新增一个控件支持这一点？

![image](https://user-images.githubusercontent.com/25057508/88071729-c9ddfe00-cba6-11ea-93ef-991a38aee6b7.png)

**Comment by ShixiangWang** [comment]
@Byronxy 找不到直接下载 CCLE 表型数据的官方操作，你可以直接把文件内容 https://data.broadinstitute.org/ccle_legacy_data/cell_line_annotations/CCLE_sample_info_file_2012-10-18.txt 存进包里，或者在代码中 使用 R 自带的 download.file() 函数进行下载

**Comment by ShixiangWang** [comment]
这个 issue 是不是完成了？

**Comment by Byronxy** [comment]
> 这个 issue 是不是完成了？

对的

**Comment by ShixiangWang** [comment]
OK，那我关闭了。
