### ISSUE TITLE
能否添加单个基因在正常组织和肿瘤的表达选项

### ISSUE THREAD

**Issue by zhaoliang0302** [openbiox/UCSCXenaShiny#121]
目前的是单基因在泛癌中的表达，如果我只对某一种肿瘤感兴趣，能否添加单癌种选项。此外，再增加TCGA数据库和TCGA+Gtex数据库两种选项，增设添加散点、小提琴的选项？

**Comment by Byronxy** [comment]
> 目前的是单基因在泛癌中的表达，如果我只对某一种肿瘤感兴趣，能否添加单癌种选项。此外，再增加TCGA数据库和TCGA+Gtex数据库两种选项，增设添加散点、小提琴的选项？

可以

**Comment by Byronxy** [comment]
> 目前的是单基因在泛癌中的表达，如果我只对某一种肿瘤感兴趣，能否添加单癌种选项。此外，再增加TCGA数据库和TCGA+Gtex数据库两种选项，增设添加散点、小提琴的选项？

该模块已经更新
![image](https://user-images.githubusercontent.com/28949856/88494029-c2738600-cfe6-11ea-977e-2e1eebe68be9.png)
