### ISSUE TITLE
专刊投稿

### ISSUE THREAD

**Issue by ShixiangWang** [openbiox/UCSCXenaShiny#145]
投下 Y 叔组织的专刊 https://mp.weixin.qq.com/s/_ZGkiG1O90g61v7E_rlaMw

https://www.frontiersin.org/research-topics/17918/biomedical-data-visualization-methods-and-applications#overview

大家关注下，投稿之前需要准备做一些事情：

- [x] 尽量解决之前 issue 的一些问题，发布第一个 1.0 版本
- [x] 准备和修改投稿的图文

大家有空可以参与讨论下。

**Comment by ShixiangWang** [comment]
@Byronxy 投稿是你建议的，目前有没有展示内容的想法？

我目前觉得有两方面的开发工作要做：

1. 完善和优化目前的功能和展示效果
2. 开发一些新的重要的特性

**Comment by ShixiangWang** [comment]
![image](https://user-images.githubusercontent.com/25057508/110267700-51279700-7ffb-11eb-8022-0ad193467fd2.png)

月底之前要提交一个摘要

**Comment by Byronxy** [comment]
> @Byronxy 投稿是你建议的，目前有没有展示内容的想法？
> 
> 我目前觉得有两方面的开发工作要做：
> 
> 1. 完善和优化目前的功能和展示效果
> 2. 开发一些新的重要的特性

数据展示方面，我整理一下之前的一些issue，然后点对点开发。然后新的特性我觉得大家一起开一个会议讨论一下

**Comment by Byronxy** [comment]
> ![image](https://user-images.githubusercontent.com/25057508/110267700-51279700-7ffb-11eb-8022-0ad193467fd2.png)
> 
> 月底之前要提交一个摘要

摘要的话以之前的预印本为基础，按照杂志的要求扩充一下就可以了。主要是上一个问题，需要在这几个月以内解决

**Comment by ShixiangWang** [comment]
准备在两个月左右内弄好。

这周五晚上 8:00-10:00 点大家有时间吗？开个腾讯视频语音会议？

**Comment by ShixiangWang** [comment]
准备在两个月左右内弄好。

这周五晚上 8:00-10:00 点大家有时间吗？开个腾讯视频语音会议？

**Comment by Byronxy** [comment]
> 准备在两个月左右内弄好。
> 
> 这周五晚上 8:00-10:00 点大家有时间吗？开个腾讯视频语音会议？

没问题

**Comment by xchromosome219** [comment]
CNV 方面我可以提供之前我的一些cnv code，如果有需要的話。
Haitao

**Comment by ShixiangWang** [comment]
@xchromosome219 代码处理的输入数据是 Xena 提供的格式吗？

**Comment by xchromosome219** [comment]
估計要改成你的包的格式

**Comment by ShixiangWang** [comment]
@xchromosome219 是独立的函数吗？输入数据是什么，处理分析的目标是什么？

**Comment by xchromosome219** [comment]
我整理一下发给你看看吧

**Comment by ShixiangWang** [comment]
目前 xena 平台只支持基因表达、和突变，以及sample type 的选择

![image](https://user-images.githubusercontent.com/25057508/112087641-49eeb480-8bc9-11eb-9baf-4b0ee6f880bc.png)

![image](https://user-images.githubusercontent.com/25057508/112087654-5115c280-8bc9-11eb-96de-e0780fad5cff.png)

**Comment by ShixiangWang** [comment]
大家有空可以多看看目前 xena 支持的分析的一些不足和问题，方便写文章比较

https://xenabrowser.net/

**Comment by ShixiangWang** [comment]
@xchromosome219 药敏代码有整理好嘛？

**Comment by xchromosome219** [comment]
我在整理 sorry to late

**Comment by ShixiangWang** [comment]
目前还没有送审，接下来一周应该会有动作了吧。。。

**Comment by ShixiangWang** [comment]
Just to test.

/remind me to check the submission status in a day.

**Comment by ShixiangWang** [comment]
/remind me to check the submission status in a day.

**Comment by ShixiangWang** [comment]
I am closing this issue as it probably not needed any more.
