### ISSUE TITLE
单基因分析功能参考

### ISSUE THREAD

**Issue by Byronxy** [openbiox/UCSCXenaShiny#153]
#  Gene-Gene Correlation
## Ref1
Wang J, Sun J, Liu L N, et al. Siglec-15 as an immune suppressor and potential target for normalization cancer immunotherapy[J]. Nature medicine, 2019, 25(4): 656-666.
![image](https://user-images.githubusercontent.com/28949856/111874130-b05bb300-89ce-11eb-8c58-3d80fd215d63.png)
 The inverse correlation of mRNA expression levels between Siglec-15 and T cell signature genes (CD3E, IFNG, GZMA and GZMB) in bladder cancer by meta-analysis of TCGA databases. Pearson r score and P value are shown (n = 407 human samples).

**Comment by ShixiangWang** [comment]
https://mp.weixin.qq.com/s/YwzR_YFodJiC6FhtOEgSUw 这个作为以后拓展的参考

**Comment by ShixiangWang** [comment]
相关分析已有实现。
