### ISSUE TITLE
vis 系列函数与 Shiny 接口

### ISSUE THREAD

**Issue by ShixiangWang** [openbiox/UCSCXenaShiny#185]
@Byronxy 

存在问题需要检查的地方：

- https://github.com/openbiox/UCSCXenaShiny/blob/1a163b3dcf3c7df79a095d2f01a0de34d48b2498/R/vis_pancan_value.R#L810
- https://github.com/openbiox/UCSCXenaShiny/blob/1a163b3dcf3c7df79a095d2f01a0de34d48b2498/R/vis_pancan_value.R#L889

整个系列函数的逻辑和运行需要再检查和运行一遍： https://github.com/openbiox/UCSCXenaShiny/blob/v1/R/vis_pancan_value.R#L889

注意有1 2 个函数有 data_type 限制，不要提供相应的 Shiny 选项，例如 https://github.com/openbiox/UCSCXenaShiny/blob/1a163b3dcf3c7df79a095d2f01a0de34d48b2498/R/vis_pancan_value.R#L49-L51

注意全部的 data_type 包括：

```
"mRNA", "transcript", "protein", "mutation", "cnv" (-2, -1, 0, 1, 2),
"cnv_gistic2", "methylation", "miRNA"
```

cnv 和 cnv_gistic2 都是 GISTIC2 的结果，一个是阈值分割后的，只有整数值。

上面修改或理解后再更新对应的 Shiny 模块，这部分算基本完成了。

目前 vis 系列函数有 10 个绘图函数接口，Shiny 端还有些没加上，像干性、TMB等，需确定和添加。

**Comment by ShixiangWang** [comment]
整个 vis pancan 文件的代码逻辑再系统检查一遍，避免代码问题和生物背景问题。这些简单实用的功能正式发表后应该有很多人使用。

**Comment by ShixiangWang** [comment]
Shiny 端绘图需要优化成点击搜索按钮再绘图

**Comment by Byronxy** [comment]
> Shiny 端绘图需要优化成点击搜索按钮再绘图

这个已经修复

**Comment by ShixiangWang** [comment]
组合的分析也需要优化下，包括支持多数据类型，主题更新（更适合发表） 支持数据导出等

![image](https://user-images.githubusercontent.com/25057508/115143340-425fe580-a079-11eb-84e5-ea0cba7eee09.png)

**Comment by Byronxy** [comment]
> 组合的分析也需要优化下，包括支持多数据类型，主题更新（更适合发表） 支持数据导出等
> 
> ![image](https://user-images.githubusercontent.com/25057508/115143340-425fe580-a079-11eb-84e5-ea0cba7eee09.png)

这个感觉会不会有点多余，我觉得这个部分可以去掉

**Comment by ShixiangWang** [comment]
你说的有到底，可以删除，避免复杂。

**Comment by ShixiangWang** [comment]
@Byronxy 你把 Comb相关代码删除吧。然后上面提到的问题有空的时候都尽快解决下。

**Comment by Byronxy** [comment]
> @Byronxy
> 
> 存在问题需要检查的地方：
> 
> * https://github.com/openbiox/UCSCXenaShiny/blob/1a163b3dcf3c7df79a095d2f01a0de34d48b2498/R/vis_pancan_value.R#L810
> * https://github.com/openbiox/UCSCXenaShiny/blob/1a163b3dcf3c7df79a095d2f01a0de34d48b2498/R/vis_pancan_value.R#L889
> 
> 整个系列函数的逻辑和运行需要再检查和运行一遍： https://github.com/openbiox/UCSCXenaShiny/blob/v1/R/vis_pancan_value.R#L889
> 
> 注意有1 2 个函数有 data_type 限制，不要提供相应的 Shiny 选项，例如
> 
> https://github.com/openbiox/UCSCXenaShiny/blob/1a163b3dcf3c7df79a095d2f01a0de34d48b2498/R/vis_pancan_value.R#L49-L51
> 
> 注意全部的 data_type 包括：
> 
> ```
> "mRNA", "transcript", "protein", "mutation", "cnv" (-2, -1, 0, 1, 2),
> "cnv_gistic2", "methylation", "miRNA"
> ```
> 
> cnv 和 cnv_gistic2 都是 GISTIC2 的结果，一个是阈值分割后的，只有整数值。
> 
> 上面修改或理解后再更新对应的 Shiny 模块，这部分算基本完成了。
> 
> 目前 vis 系列函数有 10 个绘图函数接口，Shiny 端还有些没加上，像干性、TMB等，需确定和添加。

- Gene相关性模块的bug已经修复
- 先把已经做好的模块再检查一下
- 后面stemness以及TMB的我再构思一下

**Comment by Byronxy** [comment]
参考
https://academic.oup.com/bib/advance-article/doi/10.1093/bib/bbab013/6135369?searchresult=1
![image](https://user-images.githubusercontent.com/28949856/115507025-2a24dc00-a2ae-11eb-9488-37d3111ed570.png)

**Comment by ShixiangWang** [comment]
@Byronxy 这个图我初看都看不懂，如果实现复杂可以先不关注它。



![image](https://user-images.githubusercontent.com/25057508/115508198-9f44e100-a2af-11eb-8c05-efc173ba95d8.png)

目前 CCLE 单基因表达分布和基因基因相关性参考 TCGA 类似的模块尽量先实现它。CCLE 应该同时有肿瘤和正常组织的数据，另外支持类似 TCGA 分肿瘤位点的展示对比即可。目前的模块不需要 phenotype 设定，同一个 primary site 的细胞系数据类似 TCGA 癌症类型作为一组。

![image](https://user-images.githubusercontent.com/25057508/115508626-1ed2b000-a2b0-11eb-8b5f-bb9d9e43f189.png)

**Comment by Byronxy** [comment]
> CCLE 单基因表达分布和基因基因相关性参考 TCGA 类似的模块尽量先实现它。CCLE 应该同时有肿瘤和正常组织的数据，另外支持类似 TCGA 分肿瘤位点的展示对比即可。目前的模块

好的

**Comment by Byronxy** [comment]
https://portals.broadinstitute.org/ccle/page?gene=TP53
![image](https://user-images.githubusercontent.com/28949856/115513160-58f28080-a2b5-11eb-8570-132595d8cb47.png)
@ShixiangWang 有好的办法把数据整理成这样吗，这个CCLE做得挺好的

**Comment by ShixiangWang** [comment]
我想的就是这样的，这个类似我们的 TCGA 分不。按理说你只要拼接 CCLE 拿到的数据 然后以及 ccle_info 就可以构建出这样的数据用来画图。不能这样吗？如果你觉得有难度你把实现的函数链接发我下，我今天有空看一下。

**Comment by Byronxy** [comment]
> 我想的就是这样的，这个类似我们的 TCGA 分不。按理说你只要拼接 CCLE 拿到的数据 然后以及 ccle_info 就可以构建出这样的数据用来画图。不能这样吗？如果你觉得有难度你把实现的函数链接发我下，我今天有空看一下。

这个不是很好分吧，你觉得可以如何分

**Comment by Byronxy** [comment]
> 我想的就是这样的，这个类似我们的 TCGA 分不。按理说你只要拼接 CCLE 拿到的数据 然后以及 ccle_info 就可以构建出这样的数据用来画图。不能这样吗？如果你觉得有难度你把实现的函数链接发我下，我今天有空看一下。

从这里开始
https://github.com/openbiox/UCSCXenaShiny/blob/2f18233814163c1ab0ce4343a988eea45d5ef0f2/R/vis_ccle_value.R#L8

**Comment by ShixiangWang** [comment]
好的，我晚上检查下

**Comment by ShixiangWang** [comment]
@Byronxy 检查下下面3个函数的工作情况，我增加了 use_regline 等一些选项，你根据需要对 shiny 选项进行支持。

https://github.com/openbiox/UCSCXenaShiny/blob/743255fb48b7c8c70fae54e08bad8c1361fafde9/R/vis_ccle_value.R#L61

https://github.com/openbiox/UCSCXenaShiny/blob/743255fb48b7c8c70fae54e08bad8c1361fafde9/R/vis_pancan_value.R#L873

https://github.com/openbiox/UCSCXenaShiny/blob/743255fb48b7c8c70fae54e08bad8c1361fafde9/R/vis_pancan_value.R#L970

我比较疑问的有2点：

一是下面的 `~ gene1 + gene1` 是否正确？

https://github.com/openbiox/UCSCXenaShiny/blob/743255fb48b7c8c70fae54e08bad8c1361fafde9/R/vis_pancan_value.R#L1029

二是如何解释颜色值？？

![image](https://user-images.githubusercontent.com/25057508/115548106-a7197b00-a2d9-11eb-9a32-4316e1a386ca.png)

**Comment by Byronxy** [comment]
> @Byronxy 检查下下面3个函数的工作情况，我增加了 use_regline 等一些选项，你根据需要对 shiny 选项进行支持。
> 
> https://github.com/openbiox/UCSCXenaShiny/blob/743255fb48b7c8c70fae54e08bad8c1361fafde9/R/vis_ccle_value.R#L61
> 
> https://github.com/openbiox/UCSCXenaShiny/blob/743255fb48b7c8c70fae54e08bad8c1361fafde9/R/vis_pancan_value.R#L873
> 
> https://github.com/openbiox/UCSCXenaShiny/blob/743255fb48b7c8c70fae54e08bad8c1361fafde9/R/vis_pancan_value.R#L970
> 
> 我比较疑问的有2点：
> 
> 一是下面的 `~ gene1 + gene1` 是否正确？
> 
> https://github.com/openbiox/UCSCXenaShiny/blob/743255fb48b7c8c70fae54e08bad8c1361fafde9/R/vis_pancan_value.R#L1029
> 
> 二是如何解释颜色值？？
> 
> ![image](https://user-images.githubusercontent.com/25057508/115548106-a7197b00-a2d9-11eb-9a32-4316e1a386ca.png)

已经完成相应修改。另外这个颜色就是可视化，没有特别的含义

**Comment by ShixiangWang** [comment]
@Byronxy 啊哈，那颜色的意义何在呢？这个还是需要确定下的，不然就没有引入颜色映射的必要了。

**Comment by ShixiangWang** [comment]
@Byronxy 

https://github.com/openbiox/UCSCXenaShiny/blob/81a380548a43ec49b74bc0853c8609abec6c488a/R/vis_ccle_value.R#L123-L124

这种坐标计算方式是会产生问题的，默认示例显示都存在问题。

![image](https://user-images.githubusercontent.com/25057508/115578196-a859a080-a2f7-11eb-9010-ae2b7a15f957.png)

**Comment by ShixiangWang** [comment]
https://github.com/openbiox/UCSCXenaShiny/commit/eff75356db8d7e60428264b1bb16f874f3c0f4be 这里我做的一些修改建议改进去

包括不要有 `purity_adj == TRUE` 这种写法。

坐标定位采用相对位置：

```
ggplot2::annotate("text", label = paste0("Cor: ", round(cor_res$cor, 2), " ", cor_res$pstar, "\n", "Cor_adj: ", round(partial_cor_res$cor_partial, 2), " ", partial_cor_res$pstar), x = x + 1, y = y, size = 4, colour = "black")
```

**Comment by ShixiangWang** [comment]
@Byronxy 目前建议你直接使用 v1 分支开发，不然一些我的改动你没法及时知道和合并，在思路上就会不连贯，你修改完后还要合并不一致的修改。

**Comment by ShixiangWang** [comment]
TCGA 的搜索按钮与其他模块保持一致，放在顶部。

![image](https://user-images.githubusercontent.com/25057508/115700350-2a4dd600-a399-11eb-89ca-e09add7fcb50.png)

**Comment by ShixiangWang** [comment]
@Byronxy  y 轴数字不要旋转

![image](https://user-images.githubusercontent.com/25057508/115827702-4015d680-a43f-11eb-8407-dd19ae079ae2.png)

另外有一半的插件没有加数据表格，抽空统一加一下。

如果 `p` 是一个 ggplot2 对象，`p$data` 存储的就是绘图数据，把它导出即可。

需要和你讨论的一个点是 TCGA 基因-基因相关性Shiny展示的是一个癌症类型的数据，但 CCLE 展示的是全部 cell line 的数据，是否有必要也改成按癌症类型的？？我考虑的是不同的癌症类型，不同基因的性质可能有很大的变化。

**Comment by Byronxy** [comment]
> @Byronxy y 轴数字不要旋转
> 
> ![image](https://user-images.githubusercontent.com/25057508/115827702-4015d680-a43f-11eb-8407-dd19ae079ae2.png)
> 
> 另外有一半的插件没有加数据表格，抽空统一加一下。
> 
> 如果 `p` 是一个 ggplot2 对象，`p$data` 存储的就是绘图数据，把它导出即可。
> 
> 需要和你讨论的一个点是 TCGA 基因-基因相关性Shiny展示的是一个癌症类型的数据，但 CCLE 展示的是全部 cell line 的数据，是否有必要也改成按癌症类型的？？我考虑的是不同的癌症类型，不同基因的性质可能有很大的变化。

相应部分已经完善

**Comment by ShixiangWang** [comment]
Great work. Close is ready. 我复查下包 check 是否有问题。
