### ISSUE TITLE
当前阶段计划

### ISSUE THREAD

**Issue by ShixiangWang** [openbiox/UCSCXenaShiny#189]
开发方面：

- [x] 熊逸负责的几个单基因分析模块增改完善 https://github.com/openbiox/UCSCXenaShiny/issues/185
- [x] 龙飞加一下生存绘图数据的表格输出 https://github.com/openbiox/UCSCXenaShiny/issues/148
- [x] 顾凯、xiongyi、shixiang 负责增加 CCLE 药敏分析对应的 Shiny 模块 https://github.com/openbiox/UCSCXenaShiny/issues/148
- [x] 各位开发者有空可以开始增加自己主导开发的功能的使用文档，最后统一完善和优化 https://github.com/openbiox/UCSCXenaShiny/issues/148
- [x] 王诗翔负责增加视频教程

文章写作与投稿方面：

- [x] 正文示意图，展示 XenaShiny 架构
- [x] 正文文章 ~1200 字
- [x] 附加表格：对比不同相关工具的功能特性——UCSCXenaTools, XenaPython, UCSC Xena Browser
- [ ] ~~附加单独全面的工具使用文档~~

**Comment by ShixiangWang** [comment]
- [ ] 看到 UCSC Xena Browser 支持 genomic signature 功能特性，感觉这个还是比较有意思和有用的，我有空看能不能全面更新下以支持目前全部的模块 https://ucsc-xena.gitbook.io/project/overview-of-features/genomic-signatures

**Comment by ShixiangWang** [comment]
正文图和附加表1已完成，后续优化。

**Comment by ShixiangWang** [comment]
实现对泛癌数据获取组合生成 genomic signature 的底层支持。

![image](https://user-images.githubusercontent.com/25057508/115591923-3ab47100-a305-11eb-9d59-b163db1752f5.png)

参考：

- https://stackoverflow.com/questions/37401132/how-to-parse-a-string-into-real-equation-in-r
- https://stackoverflow.com/questions/39155701/how-to-split-a-formula-in-r/39155916

- [ ] 进一步将该特性支持到 vis_identifier 系列分析函数

**Comment by ShixiangWang** [comment]
@Byronxy 你最后有空再检查你开发的所有模块（包括内部使用函数）的逻辑哈，后面我们再相当一段时间可能都不会再改动了，所以服务逻辑要尽量正确。

**Comment by ShixiangWang** [comment]
@longfei8533 龙飞有空也可以扫读一遍目前我们包和Shiny的相关逻辑，看是否存在问题或者需要优化。

**Comment by Byronxy** [comment]
添加教程，参考：http://lifeome.net/database/hccdb/help.html

**Comment by ShixiangWang** [comment]
@Byronxy 我看看啊，刚忙完搬家的事情。目前的 Help 页面准备简化一下。

对了，目前 CCLE 可视化我后面加了一些修改，你仔细看下，然后火山图横坐标支持下 mean.diff 和 median.diff，另外支持直接 ggplot 图输出，以及2个模块加数据表输出。如果你时间不多可以找龙飞一起完成下哈。

后面把教程加上这阶段的开发算基本完成了。

**Comment by Byronxy** [comment]
> @Byronxy 我看看啊，刚忙完搬家的事情。目前的 Help 页面准备简化一下。
> 
> 对了，目前 CCLE 可视化我后面加了一些修改，你仔细看下，然后火山图横坐标支持下 mean.diff 和 median.diff，另外支持直接 ggplot 图输出，以及2个模块加数据表输出。如果你时间不多可以找龙飞一起完成下哈。
> 
> 后面把教程加上这阶段的开发算基本完成了。

我增加了ggplot2输出的选项，下载的时候可以支持下载pdf，但是显示的话只能显示plotly的结果，调了一下没有调好，就先放在这里了

**Comment by ShixiangWang** [comment]
我看看，准备今天把文字教程今天也搞完。

**Comment by ShixiangWang** [comment]
@Byronxy 你改下 drug response diff 模块的主题，我来试试 plotly 和 ggplot 输出的问题哈。

**Comment by ShixiangWang** [comment]
@Byronxy 已实现，你检查下相关的设定也是否正常工作。

**Comment by ShixiangWang** [comment]
@Byronxy @longfei8533 @kaigu1990 @qins @fei0810 @xchromosome219 准备周三左右正式发布一个 beta 版本然后用推文分享看看用户是否使用还有问题。目前请诸位在闲暇之际，通过以下命令安装和启动 Shiny 查看和测试是否存在包安装、分析逻辑、文字展示等问题。有更多时间和兴趣的可以阅读 R 包源代码和 Shiny 源代码查看是否存在一些问题。

```r
# 国内
remotes::install_git("https://gitee.com/XenaShiny/UCSCXenaShiny")
# 国外
remotes::install_github("openbiox/XenaShiny")
```

启动：

```r
library(UCSCXenaShiny)
app_run()
```

感谢诸君一同的努力，开发计划基本按预期完成！！！:)

**Comment by ShixiangWang** [comment]
剑峰已经帮忙把最新版本部署到了 hiplot 服务器，https://shiny.hiplot.com.cn/ucsc-xena-shiny 可以用来对 shiny 功能进行检查

**Comment by ShixiangWang** [comment]
- [ ] Help 网页问题

**Comment by xchromosome219** [comment]
昨天折騰了半天，還是沒裝上github version，我會看看網頁版

**Comment by xchromosome219** [comment]
安裝本地，Xena Shiny 測試意見：

1. General Analysis: Matrix-Correlation: 不能改變顏色
2. General Analysis: Group-Comparison以及Survival 功能的Preprocess時間過長-無結果
3. Quick PanCan Analysis: feature TMB 和 feature MSI 失敗 Error object of type 'closure' is not subsettable
4. Quick PanCan Analysis: CCLE Drug Response Asscociation
A) 建議把-log10（FDR）改成 -log10（pval）分辨率會進一步提高。
B) 如果dot 固定大小，顏色漸變/半透明藍色到紅色代表correlation的方向和強度，是否好過 dot 大小代表correlation的強度，加單一顏色代表方向？
5. Quick PanCan Analysis: Drug response Difference
	A) 建議添加ALL tissue together。
	B) 每個基因，每個drug，高低組之間加入pvalue。

Haitao

**Comment by ShixiangWang** [comment]
@xchromosome219 好的，针对你的反馈我再测试和修改下相关的程序。
