### ISSUE TITLE
drug 分析增强

### ISSUE THREAD

**Issue by ShixiangWang** [openbiox/UCSCXenaShiny#201]
下面文章的分析方式和 Haitao 整理的还是有一些区别的。方法应该是将细胞系按突变与否分为两组，然后比较两组在某药物刺激下的IC50值（应该也要校正tissue）。

haitao 整理的代码主要不同在于相关是直接计算的 IC50 与基因表达的相关性。方法逻辑上从我的视角看没什么问题。

图形差距比较大的在于横坐标，示例是 effect 变化，即突变/野生型 IC50，这个需要换一下。

![image](https://user-images.githubusercontent.com/25057508/116250519-5f469800-a7a0-11eb-9143-20d498822edc.png)

[gks1111.pdf](https://github.com/openbiox/UCSCXenaShiny/files/6384924/gks1111.pdf)

MANOVA 分析

**Comment by ShixiangWang** [comment]
目前 分析函数的结果返回没有 IC50 值。上述的文章和方法我自己不是很清晰，需要后续抽空仔细看一看。

**Comment by ShixiangWang** [comment]
顾凯有空可以看下这个要强化的问题

目前分析和可视化的函数见 https://github.com/openbiox/UCSCXenaShiny/blob/9830b8c418a6c53aa2169b600ab81cf7347bd757/R/analyze_gene_drug_response.R#L26， https://github.com/openbiox/UCSCXenaShiny/blob/9830b8c418a6c53aa2169b600ab81cf7347bd757/R/vis_analyze_gene_drug_response.R#L10

目前可视化函数中的横坐标需要改成类似的 effect 值，目前的 mean.diff 或 median.diff 并不一定恰当，但说不准，需要做比较。也就是说，在分析函数中看能否增加得到一个类似 effect 的数据，然后和目前的做个对比。

**Comment by ShixiangWang** [comment]
@kaigu1990 可以运行 `vis_gene_drug_response_asso()` 并过一下使用到的代码。目前已经按haitao 提供的方式实现了，但经过交流觉得横坐标展示的指标与上面提供文献的不大符合，所以需要讨论实施怎么做到类似文献的分析图。也就是在 `analyze_gene_drug_response_asso` 获取到上面参考图中的 IC50 effect。

可以在微信里讨论。

**Comment by ShixiangWang** [comment]
1-2 周内彻底解决这个事。

**Comment by ShixiangWang** [comment]
记录一下

> copy number and mutation不过多因素可以放入到以后升级版中

**Comment by ShixiangWang** [comment]
@kaigu1990 你直接在下面文件的下方按照群里讨论的逻辑写一个 ` analyze_gene_drug_response_asso2` 先？后面如果觉得可以取代就将其修改为 ` analyze_gene_drug_response_asso`。建议重新拉一个分支哈，有什么问题再边做边讨论下。

https://github.com/openbiox/UCSCXenaShiny/blob/f96108bab8f8960ae6af0dc236e0167ce74e7e96/R/analyze_gene_drug_response.R#L26

**Comment by ShixiangWang** [comment]
另一篇主要的参考文献

[nature11005.pdf](https://github.com/openbiox/UCSCXenaShiny/files/6466641/nature11005.pdf)

R语言中的药物反应分析

[pone.0146021.pdf](https://github.com/openbiox/UCSCXenaShiny/files/6466646/pone.0146021.pdf)

示例：

[S1_File.pdf](https://github.com/openbiox/UCSCXenaShiny/files/6466647/S1_File.pdf)

**Comment by ShixiangWang** [comment]
[s12859-019-2608-9.pdf](https://github.com/openbiox/UCSCXenaShiny/files/6466828/s12859-019-2608-9.pdf)

这篇文章里CCLE数据用的是 activity area 进行预测。我个人觉得上述截图中3个指标是相似的，我们可以提供选项让使用者自己决定。

**Comment by ShixiangWang** [comment]
分析逻辑：

用户选择一个基因，

我们对每个药物建模
avo(药物敏感值 ~ 组织 + 表达量高低 )，这里的药敏值有4个可选数据，另外，如果用户使用 MANOVA，就将 slope 增加为一个因变量。

得到模型p值，得到FDR。

在每个组织中对细胞系按照表达高低（中位数）分为两组，计算高低两组的IC50值的均值，然后求取比值。

可视化部分以 IC50 值比值作为横坐标，P值作为纵坐标画图。

**Comment by ShixiangWang** [comment]
可以分组方式可以增加 

我们对每个药物，组织分组，建模
avo(药物敏感值 ~ 表达量 )

这个与上面不同的是我们应该可以得到不同组织下药物反应的结果，而上面的是一个泛癌水平的结果。

另外，我个人觉得这里除了 MANOVA，其他都可以直接用 lm() 建模啊。大家觉得怎么样，其实结果应该是一致的。

**Comment by ShixiangWang** [comment]
就建模方式，我自己做了个测试，显示 anova 确实是我们需要的，lm 得到每个因素下不同水平的结果。

```r
> aov(yield ~ block + N * P + K, npk)
Call:
   aov(formula = yield ~ block + N * P + K, data = npk)

Terms:
                   block        N        P        K      N:P Residuals
Sum of Squares  343.2950 189.2817   8.4017  95.2017  21.2817  218.9033
Deg. of Freedom        5        1        1        1        1        14

Residual standard error: 3.954232
Estimated effects may be unbalanced
> m1 <- aov(yield ~ block + N * P + K, npk)
> summary(m1)
            Df Sum Sq Mean Sq F value  Pr(>F)   
block        5  343.3   68.66   4.391 0.01295 * 
N            1  189.3  189.28  12.106 0.00368 **
P            1    8.4    8.40   0.537 0.47564   
K            1   95.2   95.20   6.089 0.02711 * 
N:P          1   21.3   21.28   1.361 0.26284   
Residuals   14  218.9   15.64                   
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
> m2 <- lm(yield ~ block + N * P + K, npk)
> summary(m2)

Call:
lm(formula = yield ~ block + N * P + K, data = npk)

Residuals:
   Min     1Q Median     3Q    Max 
-6.058 -1.573  0.225  2.204  5.542 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)   52.858      2.552  20.709  6.7e-12 ***
block2         3.425      2.796   1.225  0.24081    
block3         6.750      2.796   2.414  0.03005 *  
block4        -3.900      2.796  -1.395  0.18481    
block5        -3.500      2.796  -1.252  0.23117    
block6         2.325      2.796   0.832  0.41963    
N1             7.500      2.283   3.285  0.00542 ** 
P1             0.700      2.283   0.307  0.76365    
K1            -3.983      1.614  -2.468  0.02711 *  
N1:P1         -3.767      3.229  -1.167  0.26284    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 3.954 on 14 degrees of freedom
Multiple R-squared:  0.7502,	Adjusted R-squared:  0.5896 
F-statistic: 4.672 on 9 and 14 DF,  p-value: 0.005224
```

**Comment by kaigu1990** [comment]
Size effect的计算方法就选择用：“计算高低两组的IC50值的均值，然后求取比值”，这种么？

**Comment by kaigu1990** [comment]
> Size effect的计算方法就选择用：“计算高低两组的IC50值的均值，然后求取比值”，这种么？

**Comment by ShixiangWang** [comment]
对的。这就类似突变与否嘛。

**Comment by kaigu1990** [comment]
添加了`ccle_data_combined.R`用于整合清理CCLE数据集，`analyze_gene_drug_response2.R`中增加了`analyze_gene_drug_response_asso2()`函数用于替换`analyze_gene_drug_response_asso()`
当选择slope变量时，用`manova()`，当只有IC50/EC50/Amax/ActArea变量中其中一个时，用`aov()`
但是有几个问题：
* 有slope值的细胞系与药物的反应不多，因此减少了可用于方差分析的数据量，甚至有时该数据集为空，导致无法计算P值出现NA
* 之前是可以多基因计算的，但是现在的方法，需要基因表达量分组计算Size effect，那么当出现多个基因时，如何判断高表达和低表达

**Comment by ShixiangWang** [comment]
我们只支持2种情况就好了，当用户只输入一个基因名时，按中位数分组，当有多个基因名时，先求几何平均数，基因名修改为signature，然后再按中位数分组。

**Comment by ShixiangWang** [comment]
数据方面我做了一些更新，后面得再花时间把你的代码和逻辑过一遍和修改下，如果有问题再和 @kaigu1990 你讨论。

**Comment by ShixiangWang** [comment]
目前新增的药物分析代码在 https://github.com/openbiox/UCSCXenaShiny/blob/advanced_drug/R/analyze_gene_drug_response2.R，请大家帮忙检查和讨论逻辑，优化绘图以及实现 Shiny 接口。

默认示例的 TP53 结果如下：

![image](https://user-images.githubusercontent.com/25057508/118606076-903b4b00-b7e9-11eb-94e5-eed8655b52f0.png)

这个结果中有个 effect 很大，但没有显著性，比较奇怪

**Comment by ShixiangWang** [comment]
查了下这个离散值，发现是 紫杉醇，这种应该 p 值显著吧？或者说明 紫杉醇发挥作用但与 TP53 无关？

![Uploading image.png…]()

**Comment by ShixiangWang** [comment]
该药物是靶向 TUBB1的，但TUBB1的结果也不显著。。。。

![image](https://user-images.githubusercontent.com/25057508/118607252-f1afe980-b7ea-11eb-9b55-7b1b5d7367b4.png)

应该是哪里有问题

**Comment by xchromosome219** [comment]
紫杉醇跟細胞週期阻斷有關，尤其對microtube的組裝的抑制，從而抑制姐妹染色單體分離成功。與P53的相關性可以找找文獻，感覺第二版很棒，比第一版好很多，我想看看code的邏輯，還沒來得及看。

**Comment by ShixiangWang** [comment]
> 假如要用ANCOVA的话，协变量要写在自变量的前面，之前是我说错了
> 我们除了TUBB1以外，还有可以测试的基因和药物么？

不知道呢。我昨天查了下紫杉醇的工作机制如 haitao 所言，不确定该药是否影响 TUBB1 的表达。另外，我仔细检查数据后发现横坐标计算的 effect 在不同组织中差别很大，所以如果要提供该分析结果，**最好还是以某个组织而不是泛癌的结果**，泛癌的结果并不一定具备参考性。

**Comment by ShixiangWang** [comment]
从分析逻辑和目前的结果来看，都还是需要修改的，不能将误导性结果放到 Shiny 中去。

**Comment by ShixiangWang** [comment]
这个很久没关注了，且可能存在生物学问题，我关闭了，谢谢所有人的参与和讨论。
