### ISSUE TITLE
来自李唐建的反馈

### ISSUE THREAD

**Issue by ShixiangWang** [openbiox/UCSCXenaShiny#202]
- [x] 分布图 dotplot 点过大
- [x] 一些模块名加入 GTEx
- [ ] Shiny 会刷新和闪跳？？？？
- [x] TMB 分析工作不正常
- [ ] 泛癌分析增加 ICGC（后续要做的话 PCAWG一起做了）

**Comment by ShixiangWang** [comment]
@Byronxy 我对泛癌模块的数据表格展示和下载代码都清理了一遍，你复查下所以按钮是否正常工作，另外第二个模块支持的 dotplot 太大了，你有空修改下。

@Byronxy @longfei8533 @kaigu1990 你们有空的时候讨论下对 PCAWG/ICGC 增加泛癌分析模块，复用当前的模块即可。有一个需要注意它们都分 donor 和 sample 水平，后者可能更好些。ICGC 我觉得增加一个类似 TCGA 的生存分析就可以了。而 PCAWG 的数据比较丰富，可以支持目前基本 PCAWG 都支持的。

这些有一定的工作量，但我觉得比较有意义，因为 TCGA 工具的太多了。PCAWG/ICGC 的数据我们提供的分析功能就比较有创新点了。

该功能单独拉一个分支实现，完成后再合并。

- https://xenabrowser.net/datapages/?cohort=ICGC%20(specimen%20centric)&removeHub=https%3A%2F%2Fxena.treehouse.gi.ucsc.edu%3A443
- https://xenabrowser.net/datapages/?cohort=PCAWG%20(specimen%20centric)&removeHub=https%3A%2F%2Fxena.treehouse.gi.ucsc.edu%3A443&removeHub=https%3A%2F%2Fatacseq.xenahubs.net

**Comment by longfei8533** [comment]
ICGC 的数据大部分是TCGA的吧？PCAWG我还没看出来具体区别，好像是进行了肿瘤和正常组织进行了配对？

**Comment by ShixiangWang** [comment]
ICGC 可以看作独立的数据源，它是有很多 TCGA 样本，但差别很大。 PCAWG 是一个全基因组研究团队做的，就是选的 ICGC 里面质量高的数据样本，大概2700例。

**Comment by Byronxy** [comment]
![image](https://user-images.githubusercontent.com/28949856/116415254-d2691080-a86b-11eb-895c-69a90e1bc2d9.png)
相关性这里不同的组学数据有问题，本地没有问题

**Comment by ShixiangWang** [comment]
数据是指哪里有问题？

> ![image](https://user-images.githubusercontent.com/28949856/116415254-d2691080-a86b-11eb-895c-69a90e1bc2d9.png)
> 相关性这里不同的组学数据有问题，本地没有问题

**Comment by Byronxy** [comment]
> 数据是指哪里有问题？
> 
> > ![image](https://user-images.githubusercontent.com/28949856/116415254-d2691080-a86b-11eb-895c-69a90e1bc2d9.png)
> > 相关性这里不同的组学数据有问题，本地没有问题

我昨天运行的时候，这个页面一直就卡死了，我今天看没有问题

**Comment by ShixiangWang** [comment]
哦哦。那应该是后台的问题。Shiny 还是不适合开发比较高性能的服务，我们的也就勉强用用
