### ISSUE TITLE
 PCAWG开发

### ISSUE THREAD

**Issue by Byronxy** [openbiox/UCSCXenaShiny#204]
数据地址
https://xenabrowser.net/datapages/?cohort=PCAWG%20(specimen%20centric)&removeHub=https%3A%2F%2Fxena.treehouse.gi.ucsc.edu%3A443&removeHub=https%3A%2F%2Fatacseq.xenahubs.net

**Comment by ShixiangWang** [comment]
ICGC: https://xenabrowser.net/datapages/?cohort=ICGC%20(specimen%20centric)&removeHub=https%3A%2F%2Fxena.treehouse.gi.ucsc.edu%3A443

ICGC 主要做个类似 TCGA 生存分析就够了，但具体做再看看。

PCAWG 是重点，数据类型比较多。

**Comment by ShixiangWang** [comment]
我最近有空对 https://github.com/openbiox/UCSCXenaShiny/blob/9830b8c418a6c53aa2169b600ab81cf7347bd757/R/query_value.R#L65 这个函数拓展到 pcawg 和 icgc，这样上层的分析模块只需要做少量改动适配应该就能 work 了。

**Comment by ShixiangWang** [comment]
分支已创建。相关操作仅在对应分支进行。

**Comment by ShixiangWang** [comment]
一周内彻底解决这个事。

**Comment by ShixiangWang** [comment]
ICGC仔细看了下没有比较有价值有方便展示的数据，暂时不管这个数据库了。

**Comment by ShixiangWang** [comment]
@Byronxy @longfei8533  PCAWG 目前感觉有用的能采集的基本在下面了。注意与之前不同的时，同一个数据可能有不同的方法或处理。你们拉取最近的 pcawg 分支后可以运行下面的示例看看数据。

主要有：基因表达、promoter活性、基因fusion、miRNA。有个数据类型是 APOBEC 导致突变的一些指标，可用可不用。像 CNV 这种没有矩阵形式和基因水平的数据，我目前觉得不必去处理纳入。你们有空就把 TCGA 的操作拓展到 PCAWG。龙飞主要是需要完成一个生存分析模块。熊逸我看到已经做了一部分模块的拓展工作，但对应的 shiny 端数据类型需要更改下。

我感觉数据获取应该比较简单，和之前基本是兼容的，有必要再开个小会吗？或者是访问数据有问题时再讨论？

https://github.com/openbiox/UCSCXenaShiny/blob/5bcaf152af6507b1aafdfd0728b9eb6d53b76bd3/R/get_pcawg_icgc_value.R#L4-L10

**Comment by longfei8533** [comment]
> @Byronxy @longfei8533 PCAWG 目前感觉有用的能采集的基本在下面了。注意与之前不同的时，同一个数据可能有不同的方法或处理。你们拉取最近的 pcawg 分支后可以运行下面的示例看看数据。
> 
> 主要有：基因表达、promoter活性、基因fusion、miRNA。有个数据类型是 APOBEC 导致突变的一些指标，可用可不用。像 CNV 这种没有矩阵形式和基因水平的数据，我目前觉得不必去处理纳入。你们有空就把 TCGA 的操作拓展到 PCAWG。龙飞主要是需要完成一个生存分析模块。熊逸我看到已经做了一部分模块的拓展工作，但对应的 shiny 端数据类型需要更改下。
> 
> 我感觉数据获取应该比较简单，和之前基本是兼容的，有必要再开个小会吗？或者是访问数据有问题时再讨论？
> 
> https://github.com/openbiox/UCSCXenaShiny/blob/5bcaf152af6507b1aafdfd0728b9eb6d53b76bd3/R/get_pcawg_icgc_value.R#L4-L10

数据获取如果没问题，其他就没啥问题

**Comment by ShixiangWang** [comment]
@longfei8533 gene 融合应该只有 0 和 1，你可以看作类似突变处理。

**Comment by ShixiangWang** [comment]
@longfei8533 熊逸的几个模块我已经基本改好了，PCAWG 支持的 profile 你参考修改下会比较快

https://github.com/openbiox/UCSCXenaShiny/blob/0309b41d2c8ec4a9b4fc45b368eea169f572a617/inst/shinyapp/modules/modules-pcawg-search.R#L9-L22

https://github.com/openbiox/UCSCXenaShiny/blob/0309b41d2c8ec4a9b4fc45b368eea169f572a617/inst/shinyapp/modules/modules-pcawg-search.R#L105-L125

另外 PCAWG 同一种数据类型可能有不同标准化方法之类得到的结果， 为了接收额外的参数，我写了个封装函数

https://github.com/openbiox/UCSCXenaShiny/blob/0309b41d2c8ec4a9b4fc45b368eea169f572a617/R/vis_pcawg_value.R#L33

这样 `data_type = "miRNA_TMM"` 就可以在底层同时处理数据类型和额外的参数了。所以不要使用 `query_pancan_value`
