### ISSUE TITLE
install error of development version

### ISSUE THREAD

**Issue by qins** [openbiox/UCSCXenaShiny#206]
There is a installing error of development version UCSCXenaShiny.

> ERROR: dependencies ‘gmp’, ‘Rmpfr’ are not available for package ‘PMCMRplus’
> ...
> ERROR: dependency ‘pairwiseComparisons’ is not available for package ‘ggstatsplot’

Some dependencies were not installed successfully.
It would be more clear to document the dependencies installation if needs manually installation.

Environment:

> $ /usr/bin/R --version
> R version 4.0.3 (2020-10-10)
> $ uname -a
> Linux work1 5.4.0-70-generic #78-Ubuntu

**Comment by ShixiangWang** [comment]
When the package has many dependencies, it is not easy to successfully install it by one time. Specially, when you use Linux, it will compile all necessary packages built by C/C++/FORTRAN. The error shown above didn't mean that all users need to install them by hand.

My suggestion is to retry installing the packages one by one when you got an error like this.

I will try implementing the docker image in the future and also document the required packages that often cause install error.

**Comment by qins** [comment]
Thanks for the information, I'll try to figure it out.

Just let me know if there are other things I can do.

**Comment by ShixiangWang** [comment]
Thanks, I am closing now.
