### ISSUE TITLE
增加自定义数据分析

### ISSUE THREAD

**Issue by ShixiangWang** [openbiox/UCSCXenaShiny#215]
这个主要就是当用户输入自己的数据后（类似xena的格式），可以进行一些通用分析。

主要有 2 步：

- [x] 第一步：开发文件上传的模块：下下图红框处增加一个按钮，点击后弹出一个页面可以上传文件。上传界面支持2种文件上传，一个是特征文件（custom_feature_data），一个是表型文件（custom_phenotype）。每个上传框后侧需要有 upload 和 download example file 2个按钮。upload点击后会将数据保存在设定的id中。

![image](https://user-images.githubusercontent.com/25057508/124609047-dafc4980-dea1-11eb-9dc6-567b0544557e.png)

上传后对应的数据集信息也会在表格中显示出来，这样用户下面就可以点选了。

![image](https://user-images.githubusercontent.com/25057508/124609447-33334b80-dea2-11eb-985c-cca043b06dff.png)

- [x] 第二步：在server端要么将自定义数据的数据子集访问加入目前的统一实现中，要么通过条件判断进行区分处理。

**Comment by Byronxy** [comment]
之前写过上传模块的代码https://github.com/IOBR/IOBRshiny/blob/374da902ec9eba117a27ce77bb5bdc787b7328ad/app.R#L130

**Comment by ShixiangWang** [comment]
custom_feature_data 示例：（行名是特征（基因/蛋白），列名是样本名） 为了上传方面（CSV/TSV什么的），这里的行名用户可以放第一列

![image](https://user-images.githubusercontent.com/25057508/124759714-88369680-df62-11eb-9787-6b4212e31b71.png)

custom_phenotype 示例（行名是样本名，列名是各种表型分组什么的）为了上传方面，这里的行名用户可以放第一列：

![image](https://user-images.githubusercontent.com/25057508/124759803-a69c9200-df62-11eb-8820-2ffc569b2be1.png)

**Comment by Byronxy** [comment]
我做了一个简单的上传模块 @ShixiangWang 
https://github.com/openbiox/UCSCXenaShiny/blob/461f0f5dad4a0cf15cbe0cd3dcb188b8c852f9b4/inst/shinyapp/ui/general-analysis.R#L30
https://github.com/openbiox/UCSCXenaShiny/blob/461f0f5dad4a0cf15cbe0cd3dcb188b8c852f9b4/inst/shinyapp/server/general-analysis.R#L41-L67

**Comment by ShixiangWang** [comment]
我尽量明天给个反馈哈～

**Comment by ShixiangWang** [comment]
@Byronxy 我看了下你的 UI 更新。

![image](https://user-images.githubusercontent.com/25057508/125051305-66a9ec00-e0d5-11eb-85e9-0eb750989f46.png)

我的意思和意见是这样的：

1. 这个按钮没有问题，加一个文字标签 Upload/Use Your Own Data（按钮尽量靠左一点）
2. Cohort, Dataset 等等都不需要，只需要保留一个上传文件的按钮，另外在旁边提供一个 Download example file 的按钮用于下载示例文件
3. 还缺一个 custom_phenotype，用类似的格式即可。

点击后展开的页面布局大体是这样的：

```
Upload（页面的标题）

Feature-by-sample file (*.csv/.tsv)  | Download example （两个按钮）

Phenotype file (*.csv/.tsv) | Download example（两个按钮）

Note: Not both files are required. Prepare your upload files based on your analysis plan.（提示文字）
```

当 `Feature-by-sample file` 上传后，数据读入为data.frame，赋值给 `custom_feature_data `。phenotype 同理。

另外，Download example 不需要我们自己生成数据，只要提供一个链接即可。

Feature-by-sample 文件：<https://tcga-xena-hub.s3.us-east-1.amazonaws.com/download/TCGA.LAML.sampleMap%2FHiSeqV2.gz>

Phenotype 文件：<https://tcga-xena-hub.s3.us-east-1.amazonaws.com/download/TCGA.LAML.sampleMap%2FLAML_clinicalMatrix>

我的处理逻辑是第一步是独立的，第二步在处理数据的对接和设计的 Pre-selected dataset表格的问题，你这里 UI 需要用户输入一些实际上我们在 server 可以制造的数据，没有必要。

第二步我需要在你基本完成第一步的基础上集中一个时间写个初始版本再与你讨论，以及进行优化。

**Comment by ShixiangWang** [comment]
@Byronxy 上面的内容你这几天有空的时候尽快弄一下哈。

**Comment by Byronxy** [comment]
> @Byronxy 上面的内容你这几天有空的时候尽快弄一下哈。

已经更新

**Comment by ShixiangWang** [comment]
好的，我先把 回复先写了，这个周末我集中弄一下该功能的开发。

**Comment by ShixiangWang** [comment]
你先合并到主分支哈。

**Comment by ShixiangWang** [comment]
自定义数据已可以正常工作。
