### ISSUE TITLE
Further comments from Reviewer

### ISSUE THREAD

**Issue by ShixiangWang** [openbiox/UCSCXenaShiny#223]
Comparison with other tools: Although the authors now include a few sentences in the discussion for the comparison with other tools, I don’t have the feeling that this is sufficient to position UCSCXenaShiny as a unique tool in the community. To answer this point, I feel that it is necessary to include a table into either the main text or the supplement comparing the features, downsides and purposes of the different tools (such as the ones listed in Supplementary Table S2 in addition to cBioPortal and CVCDAP).
Software installation on Linux: Although I highly appreciate the effort taken to support employing UCSCXenaShiny on Linux, I was not able to run the docker container in my setup (Debian 10). I know that creating a docker container can also be very challenging and it might also be caused by an error on my side. Still, I find it very unfortunate that the software is not easily installable on a Linux system, since Linux is very prevalent in the bioinformatics community. I would highly appreciate it if the authors could create further troubleshooting advice for Linux. The issue could also be solved by submitting UCSCXenaShiny to Bioconductor, which potentially requires a more thorough continuous integration than CRAN and the submission process involves a thorough code review.
Figure: I still have the feeling that the figure does not properly visualize the main points of the manuscript and that a table (for instance the comparison to other tools) as the display item.
Text revision:

**Comment by ShixiangWang** [comment]
目前文章处于小修即可接收。

关于比较和主图修改大家有什么建议吗？

**Comment by ShixiangWang** [comment]
附表已添加。

**Comment by ShixiangWang** [comment]
第二点我回复也写了，目前如果熊逸在Ubuntu上测试docker有什么问题的话，我再进行修改。

**Comment by Byronxy** [comment]
> 第二点我回复也写了，目前如果熊逸在Ubuntu上测试docker有什么问题的话，我再进行修改。

## 使用Ubuntu 18.04进行测试
```
docker pull shixiangwang/ucscxenashiny
```
![image](https://user-images.githubusercontent.com/28949856/126898123-8da039bf-5d52-498b-b261-730ef4290a08.png)
```
docker run -d --name xenashiny -p 3838:3838 shixiangwang/ucscxenashiny
```
![image](https://user-images.githubusercontent.com/28949856/126898133-5046840f-e459-4ef5-b695-e0688213a456.png)
![image](https://user-images.githubusercontent.com/28949856/126898137-25828bfe-c0e3-423b-9d1f-6217564d021a.png)

**Comment by ShixiangWang** [comment]
Thanks @Byronxy.
