### ISSUE TITLE
update zenodo link

### ISSUE THREAD

**Issue by ShixiangWang** [openbiox/UCSCXenaShiny#227]
之前的有点过时了

- https://github.com/openbiox/UCSCXenaShiny/blob/aa818764aa3d3cb72089df9ab8458c3989ebc22c/R/load_data.R#L35
- https://github.com/openbiox/UCSCXenaShiny/blob/78b9468f8f67fabbd86519c0c8dc00c7e5ae2fe1/inst/shinyapp/modules/modules-pancan-radar.R#L75

在熊逸添加新的数据集后一起更改。

**Comment by ShixiangWang** [comment]
好

**Comment by ShixiangWang** [comment]
使用 `data <- load_data("pancancer_conserved_immune_subtype")` 从远程下载和载入数据

**Comment by ShixiangWang** [comment]
@Byronxy 测试已经通过。可以使用了。你基于上面的加载规则拓展功能吧～ 记得先拉取主分支更新

**Comment by Byronxy** [comment]
@ShixiangWang 请再更新两个数据
https://github.com/openbiox/UCSCXenaShiny/blob/60b93fad9229c5de18f0a3d838bf206bd56e8142/data-raw/raw-data-collection-and-tidying.R#L194-L206
保存在了：
https://github.com/openbiox/UCSCXenaShiny/blob/xy/data-raw/tcga_armcalls.rda
https://github.com/openbiox/UCSCXenaShiny/blob/xy/data-raw/tcga_dan_repair.rda

**Comment by ShixiangWang** [comment]
好的，`dan`会修正为`dna`。

**Comment by ShixiangWang** [comment]
- https://zenodo.org/record/5548587/files/tcga_armcalls.rda
- https://zenodo.org/record/5548587/files/tcga_dna_repair.rda

**Comment by Byronxy** [comment]
目前已经更新了一些数据了，文档我们能否更新一下呢？

**Comment by ShixiangWang** [comment]
可以的，可以写在 load_data() 函数的文档中。

我先修改下，你再补充下。

**Comment by Byronxy** [comment]
> 可以的，可以写在 load_data() 函数的文档中。
> 
> 我先修改下，你再补充下。

好的，没问题

**Comment by ShixiangWang** [comment]
对数据集进行了统一描述，你看看有问题没，修改校对下。

https://github.com/openbiox/UCSCXenaShiny/blob/a21a668bdab952cbc846ab5a90548c59dc36484e/R/load_data.R#L9-L37

显示效果：

https://openbiox.github.io/UCSCXenaShiny/reference/load_data.html

**Comment by Byronxy** [comment]
> 对数据集进行了统一描述，你看看有问题没，修改校对下。
> 
> https://github.com/openbiox/UCSCXenaShiny/blob/a21a668bdab952cbc846ab5a90548c59dc36484e/R/load_data.R#L9-L37
> 
> 显示效果：
> 
> https://openbiox.github.io/UCSCXenaShiny/reference/load_data.html

挺好的，没问题
