### ISSUE TITLE
Formula as Gene 

### ISSUE THREAD

**Issue by guillaumecharbonnier** [openbiox/UCSCXenaShiny#229]
Dear devs,

Many thanks for your wonderful tool. 

I have just tried to use a formula for the Gene argument and I am facing this issue. 

```r
> vis_toil_TvsN_cancer(Gene="PTEN / CD3E")
```
```
Querying multiple identifiers at the same time for genomic signature...
IDs include PTEN, CD3E
Warning in value[[3L]](cond) :
  Query and evaluate failed, bad IDs or formula or data values.
All NAs returned, return NULL instead.
NULL
```

Is it a feature that is not implemented yet?

**Comment by ShixiangWang** [comment]
@guillaumecharbonnier Hi, thanks for reporting.

It seems a bug in `purrr` package causing bad parameter transfer. I have rewritten the code to query data of gene list with `lapply` in the latest commint https://github.com/openbiox/UCSCXenaShiny/commit/62565003fbf5f5736b62b31560154c5c0c2aff96.

Could you try installing the latest version from GitHub and try this again? It should work now.

**Comment by ShixiangWang** [comment]
An issue has been posted on https://github.com/tidyverse/purrr/issues/844

**Comment by guillaumecharbonnier** [comment]
Thank you for this quick fix!

**Comment by ShixiangWang** [comment]
You are welcome.
