### ISSUE TITLE
Issue formulas of gene names with [-] (MT-ND1 + MT-CO1) do not plot

### ISSUE THREAD

**Issue by quiquemedina** [openbiox/UCSCXenaShiny#234]
December 10th, 2021

Greetings!

When querying with signatures (formulas containing gene names), if the gene names contain the separator “–”, example (MT-ND1 + MT-CO1), the APP does not provide plot outputs for signatures nor generate the corresponding data frames (blank output)
Notably, the individual genes plot fine, but their signatures (+, -, *. /, etc.) do not plot.

See the attachments for two examples.

Regards,

[Issue formulas of gene names with [-]  (MT-ND1 + MT-CO1) do not plot.pdf](https://github.com/openbiox/UCSCXenaShiny/files/7694096/Issue.formulas.of.gene.names.with.-.MT-ND1.%2B.MT-CO1.do.not.plot.pdf)
Enrique

**Comment by ShixiangWang** [comment]
Hi

Could you make sure you are using the latest version？And see if the problem still occur？

remotes::install_github("openbiox/UCSCXenaShiny")

**Comment by ShixiangWang** [comment]
Also，please make sure set space between operators. We use space to detect if the user input a signature instead of a gene

**Comment by quiquemedina** [comment]
Dear Shixiang,

Yes, I am using the last version (UCSCXenaShiny v1.1.4 based on
UCSCXenaTools v1.4.7) and the issue remains.

The problem is using formulas with gene names with "-" in them [(MT-ND1 +
MT-CO1)] (spacing the operator plus).

When using the genes separately MT-ND1 or MT-CO1, I get a plot, but when
using both names in a formula, I get no plot.

Enrique


Prof. Dr. Enrique Medina-Acosta, M.Sc., PhD.
MyORCID <http://orcid.org/0000-0002-2529-0548>
MyLoop <https://loop.frontiersin.org/people/51475/overview>
MyCVLattes - CNPq <http://lattes.cnpq.br/0494533350878531>

MyPublons <https://publons.com/researcher/1387178/enrique-medina-acosta/>


Senior Associate Professor

Unit Coordinator - Molecular Identification and Diagnostics Unit - NUDIM
Laboratory of Biotechnology, Center for Biosciences and Biotechnology
Universidade Estadual do Norte Fluminense Darcy Ribeiro - UENF
Building P4, rooms 212/228
Avenida Alberto Lamego 2000, Parque Califórnia, CEP 28013-602, Campos dos
Goytacazes, RJ, Brazil.
Tel: +55 22 27397085

Preferred pronouns: he, his









Em sex., 10 de dez. de 2021 às 21:34, Shixiang Wang <
***@***.***> escreveu:

**Comment by ShixiangWang** [comment]
@quiquemedina Thanks for your feedback. I will check ASAP and get back to you. :)

**Comment by ShixiangWang** [comment]
The issue is caused by the failed parse of the input expression:

The two genes are splitted into different part because it has `-` symbol.

```
> all.vars(parse(text = "MT-ND1 + MT-CO1"))
[1] "MT"  "ND1" "CO1"
```

In R, we have to use \` to avoid this.

```R
> all.vars(parse(text = "`MT-ND1` + `MT-CO1`"))
[1] "MT-ND1" "MT-CO1"
```

So you should input using the second way.

Also you need to reinstall the package from GitHub again.

![image](https://user-images.githubusercontent.com/25057508/145746704-240626fe-6a5b-4c79-a7d7-2c270f8d3ee0.png)

**Comment by ShixiangWang** [comment]
A new version is released on CRAN. You can directly install the latest version from CRAN with `install.packages` soon.

**Comment by quiquemedina** [comment]
I see. Querying for signatures as (`MT-ND1` + `MT-CO1` + `MT-CO2`) are now plotting just fine. 

Thank you for the explanation.

Enrique
