### ISSUE TITLE
Error in shinythemes::shinytheme("flatly")

### ISSUE THREAD

**Issue by victor-lopes2** [openbiox/UCSCXenaShiny#240]
I am getting the  following error message during the <app_run> execution in RStudio:

_Error in shinythemes::shinytheme("flatly") : 
  flatly is not an available theme. Valid themes are: .
In addition: Warning message:
In bslib::page_navbar(..., title = title, id = id, selected = selected,  :
  Unable to infer a `window_title` default from `title`. Consider providing a character string to `window_title`.

Could you help me resolvindg the issue?

**Comment by ShixiangWang** [comment]
@victor-lopes2 Sorry for the late delay. I guess you are using a really old-versioned R and Shiny. Could you try updating them? Or please pull the latest version of UCSCXenaShiny from GitHub and try how it works, I modified the theme setting, if the 'flatly' is not available, default theme from Shiny is used.
