### ISSUE TITLE
Radar plot “stemness” does not plot the “ACC” tumor type

### ISSUE THREAD

**Issue by quiquemedina** [openbiox/UCSCXenaShiny#242]
Dear developers,

I kindly request to address the following (bug) issue:

Radar visualization of correlation between Gene and Tumor Stemness: the radar plot does not show the “ACC” tumor types (n=32 tumor types plotted, instead of n=33), although the data table (.csv) includes all n=33 tumor types. This “visualization error” occurs in the ‘app.run’ and within the RStudio.

I attached an example snapshot view of the issue.

Yours,

Enrique Medina-Acosta
[ACC stemness radar issue.pdf](https://github.com/openbiox/UCSCXenaShiny/files/8531696/ACC.stemness.radar.issue.pdf)

**Comment by Byronxy** [comment]
Hi Enrique,

Your issue has been fixed. Thanks for your feedback. Please reinstall the updated version.

![image](https://user-images.githubusercontent.com/28949856/164506689-9a77c1ff-ebc1-4734-9064-71ce9da2bc4e.png)
