### ISSUE TITLE
GDC TARGET-OS survival analysis – gene signature -WARNING MESSAGE The column you selected seems to have no valid data.

### ISSUE THREAD

**Issue by quiquemedina** [openbiox/UCSCXenaShiny#244]
Dear developers,
Thank you so much for the expedited actions to resolve our queries.
While querying gene signatures (see examples below) in any visualization function (example, Survival analysis) with the Quick PanCan Analysis mode is working nicely, we noticed that the querying of such signatures with other repositories (example: GDC TARGET-OS) results in the notification WARNING MESSAGE The column you selected seem to have no valid data.
Here are the steps we follow:
1.	Repository
2.	GDC
3.	Cohort name: GDC TARGET-OS
4.	Data types selected: Phenotype and Genomic matrix
5.	Analyze data
6.	Survival Analysis
a.	Select dataset for grouping: TARGET-OS.htseq_counts.csv
b.	Dataset 1 molecule identifier: (GAS5 + LINC01060)
Gene signature 01: (GAS5 + LINC01060)
Gene signature 02: (`PARD6G-AS1` + `UNC5B-AS1` + GAS5 + LINC01060)
c.	Select survival dataset: TARGET-OS.survival.tsv
d.	Preprocess: WARNING MESSAGE The column you selected seems to have no valid data
e.	Submit: Error to query data ad plot. Please make sure you have gone through the ´pre-process` step 
7.	NOTE: the gene signatures’ components run fine separately.

Thank you,

Enrique Medina-Acosta, Ph.D.

Warning message
Attached pdf

Error message
Attached pdf

[GDC TARGET-OS survival analysis – gene signature -WARNING MESSAGE.pdf](https://github.com/openbiox/UCSCXenaShiny/files/8577518/GDC.TARGET-OS.survival.analysis.gene.signature.-WARNING.MESSAGE.pdf)

**Comment by ShixiangWang** [comment]
@quiquemedina  Again, thanks for your feedback. We will look into it ASAP :)

**Comment by ShixiangWang** [comment]
@quiquemedina Thanks for your report. This is a bug in querying data for gene signature. Now please update the tool from GitHub and you would find it works now. :)

<img width="991" alt="image" src="https://user-images.githubusercontent.com/25057508/165714526-c2846bd3-ad19-401a-9016-8fac006eafaf.png">

**Comment by quiquemedina** [comment]
'app.run" performing fantastic! many thanks. Enrique
