### ISSUE TITLE
Pan-cancer analysis 

### ISSUE THREAD

**Issue by xiw588** [openbiox/UCSCXenaShiny#250]
Hi Shixiang, 

Thank you for developing such a wonderful tool! I am wondering if we can do the following two pan-cancer tasks using the interactive shiny web. I have selected the right datasets in the repository and try to move on to the general analysis module, but it seems not working well. 

1) Discover the correlation between certain mutation and certain gene expression in the pan-cancer setting. 
i.e., KRAS expression by KRAS mutation (WT vs. Mutant) - A big boxplot in the pan-cancer setting as well as multiple box plots by cancer types will be ideal. 

2) Discover and download the list of differentially expressed genes regarding certain mutation status. 
i.e., Obtain all the differential gene expression including both up and down-regulated ones regarding KRAS mutation status in the pan-cancer setting. Having obtained the list of differentially expressed genes, we can conduct subsequent pathway enrichment analysis. 

If these two tasks cannot be done through the current interactive app, I am wondering if you readily have R script to efficiently run on terminal or locally. 

Thank you very much for your time and help!!

**Comment by ShixiangWang** [comment]
@xiw588  Thanks for your great suggestions. As your requests have not been considered in the previous design, thus it is not available. Also, we have no ready script for the tasks.

I will mark this as an enhancement feature, it would and should be implemented at some time, but I cannot guarantee a quick implementation as the tool is not in active development.

**Comment by ShixiangWang** [comment]
@xiw588 For your first feature, @lishensuo has implemented it. So you can install the latest version of this package and test it locally. For Feature 2, I think it's a little bit resource-consuming, @lishensuo what's your opinion about this, and would you like to take a try on implementing it? If it's okay, packages like DESeq2 should be added as suggested package in DESCRIPTION file.

**Comment by lishensuo** [comment]
I think some issues need to be considered to implement the feature:
(1) It would cost lots of time and catch to download all gene expression matrix before differentially expression analysis(DEA);
(2) The toil dataset used now is based on log2(tpm+0.001) normalization which is not suitable for some DEA package, like DESeq2
So, is it possible to support one-gene DEA mode and just use simple [wilcoxon test](https://mp.weixin.qq.com/s/_zRJNwLMnI29xpjFy_fReQ) for p value. The log2FC can be calculated theoretically by subtraction of mean log2(tpm+0.001) between 2 groups. Then, it depends on users to perform single gene, or some genes or all genes analysis just using loop statements and multi-threads parallel can be used to speed up. 

What do you think of this idea?

**Comment by xiw588** [comment]
Thank you Shixiang and the team for keeping improving the package and platform! It's such a great resource!

**Comment by ShixiangWang** [comment]
> I think some issues need to be considered to implement the feature: (1) It would cost lots of time and catch to download all gene expression matrix before differentially expression analysis(DEA); (2) The toil dataset used now is based on log2(tpm+0.001) normalization which is not suitable for some DEA package, like DESeq2 So, is it possible to support one-gene DEA mode and just use simple [wilcoxon test](https://mp.weixin.qq.com/s/_zRJNwLMnI29xpjFy_fReQ) for p value. The log2FC can be calculated theoretically by subtraction of mean log2(tpm+0.001) between 2 groups. Then, it depends on users to perform single gene, or some genes or all genes analysis just using loop statements and multi-threads parallel can be used to speed up.
> 
> What do you think of this idea?

Hi, I agree with point 2. Considering the resource limit, I think we need to limit the gene number to ~100 (set as a default parameter), and users can renew the parameter.

**Comment by xiw588** [comment]
Hi Shixiang and lishensuo, Thank you so much for your discussion and considering to implement the function. Given the concerns you raised about the large gene expression data, I wonder if it is possible to just provide a function for DE regarding mutation status based on the user uploaded dataset. In other words, you don't have to include all the gene expression matrix in the package, rather users can load the gene expression matrix themselves and this allows them to even run this analyses using their own in-house mutation and transcriptomics data. https://www.mutarget.com/analysis?type=target

**Comment by ShixiangWang** [comment]
> Hi Shixiang and lishensuo, Thank you so much for your discussion and considering to implement the function. Given the concerns you raised about the large gene expression data, I wonder if it is possible to just provide a function for DE regarding mutation status based on the user uploaded dataset. In other words, you don't have to include all the gene expression matrix in the package, rather users can load the gene expression matrix themselves and this allows them to even run this analyses using their own in-house mutation and transcriptomics data. https://www.mutarget.com/analysis?type=target

This is possible for function API, but not suitable for Shiny.

**Comment by ShixiangWang** [comment]
@lishensuo I don't know if the https://github.com/immunogenomics/presto package could help fastly compute the results from wilcox test for our data analysis on UCSC Xena datasets.

**Comment by lishensuo** [comment]
> @lishensuo I don't know if the https://github.com/immunogenomics/presto package could help fastly compute the results from wilcox test for our data analysis on UCSC Xena datasets.

OK. I will try it later.

**Comment by lishensuo** [comment]
@xiw588 Hi, we have partly achieve the feature you mentioned above. In the lastest shiny app, we support batch analysis to screen significant items upon correlation/comparison/survival analysis. However, due to the limitation of shiny ablibity, it is now not allowed to screen all genes (>10000). Up to hundreds of items batch is possible. You can refer to the latest development tutorial. https://lishensuo.github.io/posts/program/300ucscxenashiny-dev-tutorials--231119/

**Comment by ShixiangWang** [comment]
Thanks all. I am closing this issue now. Please file a new issue if further questions should be addressed.
