### ISSUE TITLE
Failure errors QuickPanCan Analysis CCLE: Drug response Association and CCLE: Drug response 

### ISSUE THREAD

**Issue by quiquemedina** [openbiox/UCSCXenaShiny#252]
The analysis with the functions CCLE: Drug response Association and CCLE: Drug response fail.
The output errors are (see print screen attached):

**Error: Data load failed 
Error: None of your input genes exist in CCLE data** (I tried more than 20 genes) 

I am running UCSCXenaShiny v1.1.9 based on UCSCXenaTools v1.4.8 from R Studio R4.2.2

Could you please verify those functionalities?

![Captura de tela 2023-02-16 145303](https://user-images.githubusercontent.com/39810494/219449831-3292fcc4-aa6c-4305-8d53-2e409cc07313.png)
![Captura de tela 2023-02-16 145245](https://user-images.githubusercontent.com/39810494/219449834-bf79c461-9cee-4a3b-b498-752d428fd971.png)
![Screenshot 2023-02-16 144649](https://user-images.githubusercontent.com/39810494/219449835-b83594c6-f392-446b-93d4-c37c88c9b69a.png)
![Screenshot 2023-02-16 144319](https://user-images.githubusercontent.com/39810494/219449836-6096ae0f-6c21-4816-bc33-e2497c1aad2e.png)
Regards
Enrique

**Comment by ShixiangWang** [comment]
Hi Enrique,

This should be a data loading issue, please check your terminal log and see if the data failed in downloading.

You can check the function at https://shiny.hiplot.cn/ucsc-xena-shiny/ , it works well.

![image](https://user-images.githubusercontent.com/25057508/219553309-39db3827-5bce-4dbd-aab5-35739994dfab.png)

**Comment by quiquemedina** [comment]
Got it!

The functions do work from [https://shiny.hiplot.cn/ucsc-xena-shiny/]. 

I´ll check my terminal log and see if the data failed in downloading.

Many thanks for the expedite and helpfull reply

Enrique
