### ISSUE TITLE
ZENODO DATA PROBLEMS

### ISSUE THREAD

**Issue by Tardins** [openbiox/UCSCXenaShiny#256]
Greetings!

When querying with signatures in Analyze Association between Gene (Signature) and Drug Response with CCLE Data, I have had some problems. The shiny showns this two messages: None of your input genes exists in CCLE data, or data load failed, try again. I would like to know if there is a problem with zenodo dataset or this could just be a bug

Regards,

Alan T.

**Comment by ShixiangWang** [comment]
@Tardins Thanks for your question. Could you try https://shiny.hiplot.cn/ucsc-xena-shiny/ and see if you can reproduce your error? If not, you may need to check your network and clean corrupted downloaded files. A detailed snapshot or reproducible code (with API functions from https://openbiox.github.io/UCSCXenaShiny/reference/index.html) will help me fix the issue.

**Comment by ShixiangWang** [comment]
@Tardins Has this issue gone now?

**Comment by Tardins** [comment]
Unfortunately I couldn't solve the problem. I tried to delete all files and packages from UCSCshiny to later perform the entire installation again, in order to replace some type of file that could be corrupted, but it did not solve the problem. I can only access the data from the zenodo dataset through the link provided in the previous email. I still don't understand where the problem could be, if in some directory of the installed files or in UCSCshiny itself. Thank you for your attention.

**Comment by ShixiangWang** [comment]
@Tardins Thanks for your feedback, in such case, I recommend you directly use the https://shiny.hiplot.cn/ucsc-xena-shiny/.
