### ISSUE TITLE
Querying chromosome coordinates, like chr1:68044026-68054909

### ISSUE THREAD

**Issue by quiquemedina** [openbiox/UCSCXenaShiny#257]
Hi developers,

I hope this message finds you well. I have a quick question about the UCSCXenaShiny app in R. Is it possible to use human chromosome coordinates, like chr1:68044026-68054909, as a query in the app instead of gene symbols? I noticed that this is possible in the UCSCXena genome browser (https://xenabrowser.net/), but it would be really helpful if this feature could also be added to the UCSCXenaShiny app.

Thank you for your time and consideration.

**Comment by ShixiangWang** [comment]
Sounds interesting! Do you mean the `chr1:68044026-68054909` should be mapped to a gene symbol? Or just it could a general coordinates with any length?

**Comment by ShixiangWang** [comment]
If using coords for general mapping, then the coords can only be used for data at specific molecular levels, such as the methylation you mentioned.

I agree with you that it's indeed import. However, as applying the feature is challenging and maybe resource-heavy, I think it probably needs some experimental design and try. Do you think where is the best place to try this feature? Or do you have specific analysis requirements for enabling this feature?

**Comment by quiquemedina** [comment]
The decision where to place the “physical coordinate query” feature to be called in the app_run (or via hiplot) will be most suitable for data sets that have genetic Information (transcriptome, 450K_methylation, CNV, mutation burden). For data, the feature will be an asset for TCGA-TARGET_GTEX datasets. For Methylation450k the feature is needed for the TARGET data set, but not dot GTEX and TARGET datasets since those do not include 450K methylation data (my reading form UCSCXena data sets).
Another aspect to keep in mind is the version for the genome to select (hg38 or hg19) for the “physical coordinate query” feature since all transcriptome datasets in the UCSCXena are responsive to hg38 but not for hg19 coordinates. On the other hand, from my experience, for Methylation450k the data sets are responsive tohg19 coordinates.
For example, TCGA BRCA hg19 coordinates for DIRAS3 (chr1:68,509,709-68,520,592) yield an accurate view of the Methylation450k in the gene region. If I were to use (incorrectly) hg38 coordinates for DIRAS3 ( chr1:68044026-68054909), the data points do not (of course) correspond to the DIRAS gene (in this example, yielding no data points).

Figure 1. Overview example for hg19 coordinated for DIRAS3 in TCGA BRCA Methylation450k data
 

 
Figure 2. INCORRECT call overview example for hg38 coordinates for DIRAS3 in TCGA BRCA Methylation450k data with no data 

 

The same logic applies to Methyaltion27K, which is only for hg19.
Yes, I imagine that implementing is challenging and maybe resource-heavy, but I assure you it will be an asset for your app_run resource tool.
Regards 
Enrique
[supporting figures.pdf](https://github.com/openbiox/UCSCXenaShiny/files/11397298/supporting.figures.pdf)

**Comment by ShixiangWang** [comment]
@quiquemedina Hi Enrique,

Thank you so much for bringing this idea to our attention and sharing your creative ideas with us. We truly appreciate your dedication to improving our tool. I will treat this feature as a focus of our next implementation and will try our best to achieve this. However, I cannot guarantee success and also it may take a few months to see if it is truly possible.

Best,
Shixiang

**Comment by ShixiangWang** [comment]
Hi @quiquemedina ,I quoted the response from Shensuo (@lishensuo). Hope you test and give some feedback on this new feature when you have time if you are still interested in this topic.

> In the latest version of shiny app, we allow users to select interesting CpG site(s) for one gene before pan-cancer analysis. And users can look for the mapping relationship from the help page of app(both 450K and 27K under hg38 genome).

**Comment by quiquemedina** [comment]
Dear  @ShixiangWang and @lishensuo,

I would like to extend my sincere thanks for implementing the robust popup features in the Pan-Can Analysis. These features, which enable scanning and selecting genes and associated CpG sites as query entries, have significantly enhanced the tool's functionality. The new features have opened up broader possibilities for testing novel hypotheses.

During my exploration of the tool, I noticed the addition of new identifiers, which have greatly intrigued me. However, I need more details about these new identifiers, especially in the drop-down menus, such as those for Tumor Stemness. This feature now includes options to filter by:
1. RNAss
2. EREG.EXPss
3. DNAss
4. EREG.METHss
5. DMPss

I would appreciate more information on these identifiers to fully utilize the tool's capabilities.

Here are the steps I followed in a case example using the new tools:

TCGA Association Analysis (New Tools)
- Gene Case Example: AFAP1L2
  - S1: Preselect Step
    1. Multi-cancers
    2. Multi-conditions: All ticked
    3. Set data origin: Pinpoint CpG per gene (AFAP1L2) - CpG sites not selected
  - S2: Select Variable for X
    - Molecule Profile
    - Data Subtype: DNA Methylation
    - Identifier: AFAP1L2
  - S3: Select Variable for Y
    - Tumor Index
    - Data Subtype: Tumor Stemness
    - Identifiers:
      a. RNAss
      b. EREG.EXPss
      c. DNAss
      d. EREG.METHss
      e. DMPss
  - S4: Analyze
    - Correlation Method: Spearman

The results I obtained for the identifier “RNAss” closely matched those I previously generated using the Quick PanCan Analysis for radar stemness versus AFAP1L2 Methylation, yielding a Spearman rho >0.1 in THYM (top hit). However, the significance and logic behind the other drop-down identifiers are not clear to me.

Could you please provide further insights into these identifiers? 

Additionally, I would be grateful if you could share the underlying R code for the above case example. I intend to implement it in a loop to query genes from a specified gene list form my RStudio UCSC XenaShiny script.

I have attached two print screens for your reference.

Best regards,

Enrique
---
Example identifier Tumor stemness: RNAss
![image](https://github.com/openbiox/UCSCXenaShiny/assets/39810494/b5ceca3e-40bd-46c3-92be-17f3b6965538)

Example identifier Tumor stemness: EREG.EXPss
![image](https://github.com/openbiox/UCSCXenaShiny/assets/39810494/56f49205-45ee-419e-915b-e7e119b06f06)
[Xena new complexities.pdf](https://github.com/openbiox/UCSCXenaShiny/files/13401524/Xena.new.complexities.pdf)

**Comment by lishensuo** [comment]
Thank you for your detailed feedback. We will provide some English tutorials for the easy use of recent updates in these days.

**Comment by lishensuo** [comment]
Here is the temporary tutorial for recent updates, which may help you. https://lishensuo.github.io/posts/program/300ucscxenashiny-dev-tutorials--231119/
As for your questions:
- Firstly, you can download the analyzed result in the bottem buttons of step S4, which would include the p.value significance;
- Secondly, our code is totally open. You can directly find the script from the Github repository. In addition, I guess loop you mentioned is to perform batch analysis on multiple items which is supported now in our shiny app. You can find the introduction from above tutorial link.
- As for the meaning of identifier, we will consider to add it to the help page in the future.
I don't know if I missed your other questions and thank you for your use feedback very much.

**Comment by quiquemedina** [comment]
Dear @lishensuo, 

Thank you for the informative  temporary tutorial. 
However, details on the Tumor Stemness drop-down identifiers will be most appreciated ASAP for assessments. 

Are those as referred in [1, 2]

“_Six tumor stemness indexes, namely differentially methylated probes-based (DMPss), DNA methylation based (DNAss), enhancer elements/DNA methylation-based (ENHss), epigenetically regulated RNA expression-based (EREG.EXPss), epigenetically regulated DNA methylation-based (EREG-METHss), RNA expression-based (RNAss)_ [2]”


1.	Malta TM, Sokolov A, Gentles AJ, et al., Machine Learning Identifies Stemness Features Associated with Oncogenic Dedifferentiation. Cell. 2018;  173(2):338-354 e15.
2.	Shi X, Feng D, Li D, et al., A pan-cancer analysis of the oncogenic and immunological roles of apolipoprotein F (APOF) in human cancer. Eur J Med Res. 2023;  28(1):190.

Enrique

**Comment by quiquemedina** [comment]
Dear @lishensuo and @ShixiangWang 

I regret to inform you that I inadvertently deleted my previous comment and request. I am attempting to reconstruct it here.

Users will urgently require detailed information about the latest enhancements to your drop-down menus, specifically those related to Tumor Stemness assessment. The feature has been updated to include options for filtering analyses based on the following criteria:

1. RNA Expression-based Stemness Score (RNAss)
2. Epigenetically Regulated RNA Expression-based Stemness Score (EREG.EXPss)
3. DNA Methylation-based Stemness Score (DNAss)
4. Epigenetically Regulated DNA Methylation-based Stemness Score (EREG.METHss)
5. Differentially Methylated Probes-based Stemness Score (DMPss)

Could you confirm if these categories are as detailed in the references here provided, namely [1, 2]? Specifically, I am referring to the study on tumor stemness, heterogeneity, and mutation landscape [2], which states: 

“Six tumor stemness indices, namely Differentially Methylated Probes-based (DMPss), DNA Methylation-based (DNAss), Enhancer Elements/DNA Methylation-based (ENHss), Epigenetically Regulated RNA Expression-based (EREG.EXPss), Epigenetically Regulated DNA Methylation-based (EREG-METHss), and RNA Expression-based (RNAss) were utilized to analyze the correlation between stemness features and APOF expression through Spearman analysis [21].”[2]

1.	Malta TM, Sokolov A, Gentles AJ, et al., Machine Learning Identifies Stemness Features Associated with Oncogenic Dedifferentiation. Cell. 2018;  173(2):338-354 e15.
2.	Shi X, Feng D, Li D, et al., A pan-cancer analysis of the oncogenic and immunological roles of apolipoprotein F (APOF) in human cancer. Eur J Med Res. 2023;  28(1):190.

Your prompt response would be greatly appreciated.

Best regards,

Enrique

**Comment by lishensuo** [comment]
Please refer to the two links where the data is downloaded:
(1) https://xenabrowser.net/datapages/?dataset=StemnessScores_RNAexp_20170127.2.tsv&host=https://pancanatlas.xenahubs.net
(2) https://xenabrowser.net/datapages/?dataset=StemnessScores_DNAmeth_20170210.tsv&host=https://pancanatlas.xenahubs.net
Hope it could help you.

**Comment by ShixiangWang** [comment]
I am closing this issue now. Any further questions please file a new issue.

**Comment by quiquemedina** [comment]
Subject: Request for R Code for TCGA Association Analysis Features in Xena hiplot

Dear @ShixiangWang ,

I am following up on my request from two weeks ago regarding the R code for the new features in TCGA Association analysis, specifically those enabling queries of CpG sites and gene coordinates (hg38) within the Xena hiplot platform.

I apologize if my repeated inquiries seem excessive. However, I have been unable to locate the relevant code in the GitHub repository [UCSCXenaShiny](https://github.com/openbiox/UCSCXenaShiny?search=1) for use in R.

Could you kindly guide me to the specific location or path where this code can be found?

To illustrate my requirement, I am particularly interested in the process for querying CpG sites associated with the RCAN2 gene in Esophageal Carcinoma (ESCA). The steps I am referring to are as follows:

1. TCGA Association Analysis
2. S1 Preset:
   a. Select cancer type: ESCA
   b. Choose modified dataset:
      i. TOIL-DNA Methylation
      ii. 450k
      iii. Gene: RCAN2
      iv. Specify minimum coordinates:
         1. 46391143
         2. 46472267
   c. Include 3 CpG sites
3. S2 Get Data:
   a. Query data
   b. Define molecular profile:
      i. Methylation
      ii. Identifier: RCAN2
   c. Further data query:
      i. Tumor index
      ii. Tumor stemness
      iii. Identifiers: RNAss
4. S3 Analysis & Visualize:
   a. Perform Correlation analysis (Spearman)

Your assistance with this matter would be greatly appreciated. Thank you for your understanding and support.

Best regards,

Enrique
