### ISSUE TITLE
Is shiny.hiplot-academic.com down worldwide?

### ISSUE THREAD

**Issue by quiquemedina** [openbiox/UCSCXenaShiny#258]
We have not been able to access https://shiny.hiplot-academic.com/ucsc-xena-shiny/
Apparently it is down not only for me but from several other servers, as tested in https://downforeveryoneorjustme.com/shiny.hiplot-academic.com?proto=https.

Thank you,

Enrique

**Comment by ShixiangWang** [comment]
Dear @quiquemedina, thanks for your report. The Hiplot URL has been changed to https://shiny.hiplot.cn/ucsc-xena-shiny/ .

**Comment by quiquemedina** [comment]
Great!

many thanks!

Prof. Dr. Enrique Medina-Acosta, M.Sc., PhD.
MyResearchGate <https://www.researchgate.net/profile/Enrique-Medina-Acosta>
My Web of Science
<https://www.webofscience.com/wos/alldb/citation-report/88b9c519-7e0a-41be-8770-1c39d0173b87-2266fe0a>
MyORCID <http://orcid.org/0000-0002-2529-0548>
MyLoop <https://loop.frontiersin.org/people/51475/overview>
MyCVLattes - CNPq <http://lattes.cnpq.br/0494533350878531>

MyPublons <https://publons.com/researcher/1387178/enrique-medina-acosta/>


Senior Associate Professor

Unit Coordinator - Molecular Identification and Diagnostics Unit - NUDIM
Laboratory of Biotechnology, Center for Biosciences and Biotechnology
Universidade Estadual do Norte Fluminense Darcy Ribeiro - UENF
Building P4, rooms 212/228
Avenida Alberto Lamego 2000, Parque Califórnia, CEP 28013-602, Campos dos
Goytacazes, RJ, Brazil.
Tel: +55 22 27397085

Preferred pronouns: he, his









Em qua., 24 de mai. de 2023 às 03:39, Shixiang Wang (王诗翔) <
***@***.***> escreveu:
