### ISSUE TITLE
Error in hiplot - Quick PanCancer analysis of the Stemness/TMI/MSI feature at https://shiny.hiplot.cn/ucsc-xena-shiny/ 

### ISSUE THREAD

**Issue by quiquemedina** [openbiox/UCSCXenaShiny#259]
Dear UCSCXena developers,

I would like to bring to your attention that the Quick PanCancer analysis of the Stemness/TMI/MSI feature at https://shiny.hiplot.cn/ucsc-xena-shiny/ is currently not functioning properly. The plots are not being generated, and the data table is also not being generated. 

Whenever I try to query any gene symbol, I encounter the following error: "Error: An error has occurred. Check your logs or contact the app author for clarification."

I suspect that this issue arose after the portal was updated to UCSCXenaShiny v1.1.10, based on UCSCXenaTools v1.4.8. It may be related to a previous problem that was reported regarding the Radar plot (ricardo-bion/ggradar).

This prior issue, possibly related (#254), was titled: "Error: Quick PanCan Analysis, TCGA: Association between Molecular Profile And TMB/Stemness/MSI (radar show) #254."

I kindly request your assistance in resolving this matter.

Thank you.

Sincerely,

Enrique

**Comment by ShixiangWang** [comment]
@quiquemedina Thanks you like always. I can reproduce this on hiplot and will look into it.

**Comment by ShixiangWang** [comment]
It seems an issue with the Hiplot server, the error is `SSL peer certificate or SSH remote key was not OK`, I am contacting the manager Jianfeng, and working on it. I checked and found that all modules that require data from Zenodo are not functioning.


```r
su: ignore --preserve-environment, it's mutually exclusive to --login.
Run mode: client
Checking depedencies...
Loading required namespace: pacman
Loading required namespace: gganatogram
Loading required namespace: ggradar
Starting...
Loading data from remote: https://zenodo.org/record/5548587/files/transcript_identifier.rda, please wait...
trying URL 'https://zenodo.org/record/5548587/files/transcript_identifier.rda'
Warning in download.file(data_url, data_path) :
  URL 'https://zenodo.org/record/5548587/files/transcript_identifier.rda': status was 'SSL peer certificate or SSH remote key was not OK'
Data load failed, please check your input and the internet.
 NULL will be returned.
Loading data from remote: https://zenodo.org/record/5548587/files/tcga_TIL.rda, please wait...
trying URL 'https://zenodo.org/record/5548587/files/tcga_TIL.rda'
Warning in download.file(data_url, data_path) :
  URL 'https://zenodo.org/record/5548587/files/tcga_TIL.rda': status was 'SSL peer certificate or SSH remote key was not OK'
Data load failed, please check your input and the internet.
 NULL will be returned.
Warning in bslib::page_navbar(..., title = title, id = id, selected = selected,  :
  Unable to infer a `window_title` default from `title`. Consider providing a character string to `window_title`.
Warning: Good news!
You don't need to call `useShinyalert()` anymore. Please remove this line from your code.
If you really want to pre-load {shinyalert} to the UI for any reason, use:
	`useShinyalert(force = TRUE)`

Listening on http://127.0.0.1:41193
Shiny app run successfully! Enjoy it!

               --  Xena shiny team

Setting mirror, use hiplot: FALSE
```

**Comment by ShixiangWang** [comment]
@quiquemedina Thanks to @Miachol, the Hiplot Xena shiny is working now.

**Comment by ShixiangWang** [comment]
@quiquemedina Enrique, thank you again :).

**Comment by quiquemedina** [comment]
@ShixiangWang -  Great! Thank you very much for taking prompt and decisive action!

Enrique
