### ISSUE TITLE
Is https://shiny.hiplot.cn/ucsc-xena-shiny/ browser down?

### ISSUE THREAD

**Issue by quiquemedina** [openbiox/UCSCXenaShiny#264]
For the last week or so, access to < https://shiny.hiplot.cn/ucsc-xena-shiny/ >is down ( using either chrome or firefox)

Here it is the error message I got: 

An error has occurred

**The application failed to start.

The application exited during initialization**.

Access from <https://shixiangwang.shinyapps.io/ucscxenashiny/> is ok but the version is UCSCXenaShiny v1.1.8 based on UCSCXenaTools v1.4.8, which has not incorporated the issues updates.

Enrique

**Comment by ShixiangWang** [comment]
Thanks, I will take a look the hiplot.

https://shixiangwang.shinyapps.io/ucscxenashiny/ is most like a demo. If the server is down, I suggest you use it locally. Sorry for the inconvenience.

**Comment by ShixiangWang** [comment]
I got the log from hiplot, seems a bug was introduced with the code update, I will see how to fix it.

```
su: ignore --preserve-environment, it's mutually exclusive to --login.
Run mode: client
Checking depedencies...
Loading required namespace: pacman
Loading required namespace: gganatogram
Loading required namespace: ggradar
Starting...
Warning in infer_window_title(title, window_title) :
  Unable to infer a `window_title` default from `title`. Consider providing a character string to `window_title`.
Warning: Good news!
You don't need to call `useShinyalert()` anymore. Please remove this line from your code.
If you really want to pre-load {shinyalert} to the UI for any reason, use:
	`useShinyalert(force = TRUE)`
Error in ui.modules_pw_cor("modules_pw_cor") : 
  object '"modules_pw_cor"' not found
Calls: runApp ... dots_list -> selectInput -> choicesWithNames -> hasGroups
Execution halted

```

**Comment by Miachol** [comment]
It works now.

**Comment by ShixiangWang** [comment]
Thank you, Jianfeng @Miachol , as always.
