### ISSUE TITLE
enhance the data query and analysis of methylation data

### ISSUE THREAD

**Issue by ShixiangWang** [openbiox/UCSCXenaShiny#266]
- [x] Custom methylation data query/filter and aggregation. https://github.com/openbiox/UCSCXenaShiny/issues/263
- [x] Data query with location? https://github.com/openbiox/UCSCXenaShiny/issues/257

**Comment by ShixiangWang** [comment]
@lishensuo 关于第1点，我记得相关的ui我让你弄一下哈，你后面有空注意下

**Comment by lishensuo** [comment]
嗯好的~

**Comment by lishensuo** [comment]
In the latest version of shiny app, we allow users to select interesting CpG site(s) for one gene before pan-cancer analysis. And users can look for the mapping relationship from the help page of app(both 450K and 27K under hg38 genome).

**Comment by ShixiangWang** [comment]
Great!

**Comment by quiquemedina** [comment]
Could you please guide me in navigating in the app_run( ) to find the new feature? In the latest version of the app installed in my PC (UCSCXenaShiny v1.1.12 based on UCSCXenaTools v1.4.8) , I could not locate the feature to look for the mapping relationship from the help page of app (both 450K and 27K under hg38 genome).

Regards, 

Enrique

**Comment by lishensuo** [comment]
Thank you for your feedback. You can see the ID reference from the following guidance.

![image](https://github.com/openbiox/UCSCXenaShiny/assets/80585985/a7dd0394-0310-4250-8cd4-6a80307e2a6e)

**Comment by quiquemedina** [comment]
I have successfully located and utilized the ID reference tool, which I found to be comprehensive and informative.
@lishensuo noted that users have the capability to select specific CpG sites for a single gene prior to conducting pan-cancer analysis. 

In my case example, for the gene RCAN2, from ID reference, I chose all available CpG sites by selecting the relevant rows. However, the process of integrating this selection with the QuickPanCan features, such as TMB, Stemness, or MSI (as depicted in the Radar Show), is not immediately clear. It would be beneficial for the user that the developers incorporate a detailed guide in the 'Help' section to facilitate this integration.

In my suggestion from May 2023, the intent was to enhance the tool's functionality by enabling analyses using a range of genomic coordinates encompassing multiple CpG sites, or a single specific CpG site.

Please, let me know if my needs are sufficiently clear

Regards,
Enrique

**Comment by lishensuo** [comment]
Sorry，I have not provide the official english tutorial for this update. In the the latest version, we mainly add the "Pan-Can Analysis" including 3 types of cancer statistical analysis. In each of analysis(correlation/comparison/survival), we support the specific CpG sites selection for one gene. However, for the primary "Quick PanCan Analysis" module, we have not updated yet.

![image](https://github.com/openbiox/UCSCXenaShiny/assets/80585985/5904aebb-96da-4ce7-a546-bc5187ed83e5)

**Comment by ShixiangWang** [comment]
Hi, @lishensuo , with the powerful popup widget, it is possible (no heavy computation) to include a feature to scan features (genes/cpg sites) based chromosomal location, as originally posted at https://github.com/openbiox/UCSCXenaShiny/issues/257?

**Comment by lishensuo** [comment]
OK. I plan to pull a request recently and will add it into next develop list.

**Comment by ShixiangWang** [comment]
> Hi, @lishensuo , with the powerful popup widget, it is possible (no heavy computation) to include a feature to scan features (genes/cpg sites) based chromosomal location, as originally posted at #257?

@lishensuo Was implemented in your latest PR, right?

**Comment by lishensuo** [comment]
> > Hi, @lishensuo , with the powerful popup widget, it is possible (no heavy computation) to include a feature to scan features (genes/cpg sites) based chromosomal location, as originally posted at #257?
> 
> @lishensuo Was implemented in your latest PR, right?

Yes. Users now can furtherly set the chromosomal location after selecting one gene to query interesting CpG sites.

**Comment by ShixiangWang** [comment]
Thanks
