### ISSUE TITLE
button layout

### ISSUE THREAD

**Issue by ShixiangWang** [openbiox/UCSCXenaShiny#271]
<img width="295" alt="image" src="https://github.com/openbiox/UCSCXenaShiny/assets/25057508/6a1e4f46-d6b0-4880-8b78-2e06318e2827">

3 个 save 按钮的排列可以再优化下 @lishensuo

**Comment by lishensuo** [comment]
嗯嗯，好的

**Comment by ShixiangWang** [comment]
http://www.pancansurvplot.com/ 一些 UI 你觉得好的方面可以参考借鉴下
