### ISSUE TITLE
UCSCXenaShiny_issue Incorrect methylation data and plot last update version - Quick PanCan Analysis' feature, particularly in the TCGA Molecule to Molecule 

### ISSUE THREAD

**Issue by quiquemedina** [openbiox/UCSCXenaShiny#278]
Dear Development Team,

Following the recent software update on November 14, 2023, I have encountered a notable inconsistency in the methylation data values compared to those in the previous version and the source data available from UCSCXena ([CAN2_UCSC_Xena_ESCA_dataframe.txt]). This discrepancy is affecting the accuracy of the generated plots.

Specifically, this issue is evident in the 'Quick PanCan Analysis' feature, particularly in the TCGA Molecule to Molecule correlation functionality, which assesses the relationship between methylation and mRNA expression. As a case in point, when analyzing the correlation between RCAN2 methylation and RCAN2 expression, the data inconsistency becomes apparent, leading to inaccurate plot representations.

This deviation from the expected data integrity is a critical concern, as it directly impacts the reliability of the analysis performed using this tool. I would appreciate it if you could investigate and resolve this issue to ensure the accuracy and reliability of the data analysis facilitated by your software.

Thank you for your attention to this matter.

Enrique
[UCSCXenaShiny_issue Incorrect methylation data and plot last update version.pdf](https://github.com/openbiox/UCSCXenaShiny/files/13381371/UCSCXenaShiny_issue.Incorrect.methylation.data.and.plot.last.update.version.pdf)

[RCAN2_UCSC_Xena_ESCA_dataframe.txt](https://github.com/openbiox/UCSCXenaShiny/files/13381583/RCAN2_UCSC_Xena_ESCA_dataframe.txt)

See attachments

**Comment by ShixiangWang** [comment]
Thank you @quiquemedina , you have my attention

**Comment by ShixiangWang** [comment]
Hi @quiquemedina , I appreciate your detailed report, which help me quick locate the bug. I checked and found that the global options introduced by @lishensuo set a non-suitable default   parameter for aggregating the methylation level. Now I have fixed it at https://github.com/openbiox/UCSCXenaShiny/commit/bcddceda345557e7cc7a7a1ec16c522aec85bc49. Could you try using the latest version and let me know if it works?

**Comment by quiquemedina** [comment]
@ShixiangWang, great to hear that everything is back to normal, as checked at my end with the data source usage and plotting as before! Thank you for your prompt and helpful assistance in resolving these issues
