### ISSUE TITLE
Recurrent Error with Composed Gene Symbols in Gene Signatures using XenaShiny

### ISSUE THREAD

**Issue by quiquemedina** [openbiox/UCSCXenaShiny#283]
[Uploading Gene signatures formatting recurrent running error with XenaShiny version updated.pdf…]()
Dear XenaShiny Developers,

I am writing to report a persistent issue we have encountered in the latest version of XenaShiny (UCSCXenaShiny v2.0.0 based on UCSCXenaTools v1.4.8). Specifically, we are facing difficulties when executing gene signatures that include gene symbols with complex names. For example, the following gene signature: (ADAMTS16 + AGBL3 + DGCR6 + EXD3 + MAGI2 + PLG + RASGRF1 + RB1 + `SNORD116-1` + SNURF + SPATA31D1 + `ZFAT-AS1` + ZNF833P) results in errors.
We observed that each composed gene symbol (e.g., `SNORD116-1`, `ZFAT-AS1`, SPATA31D1) functions correctly when run individually. However, when combined into a signature, whether formatted with or without backticks (`gene_symbol`), the process fails. For instance:
- (SPATA31D1 + ZNF833P): failed
- (`SPATA31D1` + ZNF833P): failed
- (`ZFAT-AS1` + `SNORD116-1` + SPATA31D1): failed

These errors occur despite the gene symbols running effectively in isolation (e.g., methylation vs TMB correlation analyses). The problem persists even when gene symbols are formatted as previously required by earlier versions of XenaShiny, for example: (`ZFAT-AS1` + `SNORD116-1` + SPATA31D1).

This issue is significantly impacting our analysis and we would greatly appreciate your assistance in resolving it.

Thank you for your attention to this matter.

Best regards,

Enrique
![image](https://github.com/openbiox/UCSCXenaShiny/assets/39810494/75bf5c0b-4f80-4981-a5b1-991ab471b269)

**Comment by ShixiangWang** [comment]
Hi @quiquemedina Thanks for the report. I will dig into this and fix it ASAP.

**Comment by ShixiangWang** [comment]
@quiquemedina Hi, I pushed a commit to fix this issue.

The reason why gene signature did not work is that the `SPATA31D1` has 1 sample less than other two genes, so it raised error when combining the data with unequal size.

**Comment by quiquemedina** [comment]
Thank you for fixing the bug!

Tested ok with (CASP1 + CASP12 + CDK1 + DFNA5 + SPATA31D1 + MLKL + `ZFAT-AS1` + `SNORD116-1` + NLRP1 + NLRP3 + PABPC1 + PYCARD + RIPK3 + TNFAIP3 + TNFRSF1A)

**Comment by ShixiangWang** [comment]
Good to hear that.
