### ISSUE TITLE
原始数据下载相关

### ISSUE THREAD

**Issue by soleded** [openbiox/UCSCXenaShiny#289]
请问下载原始数据选项里，只有FPKM和count两种类型，没有TPM类型的转录组数据下载方式嘛？

**Comment by ShixiangWang** [comment]
能具体说明下你的问题吗？一般来说，如果没有 TPM 的数据，对应的 UCSC Xena 可能没有提供。

你可以在 https://xenabrowser.net/datapages/ 查询。
