### ISSUE TITLE
Unable to perform CNA vs. gene expression analysis in TCGA pan-cancer 

### ISSUE THREAD

**Issue by xiw588** [openbiox/UCSCXenaShiny#309]
Hi Shixiang, 

I was trying to perform analysis on CNA and gene expression in HLA genes in the TCGA pan-cancer setting using the shiny app. Unfortunately, there have been errors all the time. Can you please help look into this? Thanks a lot!

**Comment by ShixiangWang** [comment]
@xiw588 Thanks for your response. Please show your logs/snapshots for reproducing the error so we can take a quick look at this issue.

**Comment by ShixiangWang** [comment]
Long time no response. Please raise an issue if you re-encounter this issue.
