### ISSUE TITLE
Set group.var from string failed?

### ISSUE THREAD

**Issue by ShixiangWang** [openbiox/UCSCXenaShiny#317]
https://github.com/openbiox/UCSCXenaShiny/blob/e59886b388b86903d779bda04cca3fef18b80b38/R/vis_identifier.R#L263

Link to https://github.com/IndrajeetPatil/ggstatsplot/issues/891

**Comment by ShixiangWang** [comment]
@lishensuo 有空看下标记的这个功能函数是不是受到影响，需要 fix

**Comment by lishensuo** [comment]
> @lishensuo 有空看下标记的这个功能函数是不是受到影响，需要 fix

收到
