### ISSUE TITLE
Issue with Non-Numeric Arguments in Binary Operations in UCSCXenaShiny v2.0.0

### ISSUE THREAD

**Issue by quiquemedina** [openbiox/UCSCXenaShiny#324]
Dear UCSCXenaShiny Development Team,
We are currently utilizing the UCSCXenaShiny version 2.0.0 in RStudio and have encountered a recurring error: "Error: non-numeric argument to binary operator." This issue arises when analyzing any gene or gene signature across various cancer types.

Example of Gene Signature Causing Error:
- Computation: HOXA5 + HOXA4 + HOXA3 + HOXA2 + HOXA9
![image](https://github.com/openbiox/UCSCXenaShiny/assets/39810494/2579895f-7ddb-4f2b-a4a2-128bafb65ae0)
![image](https://github.com/openbiox/UCSCXenaShiny/assets/39810494/a307116e-175a-45b8-a74d-b0458a905e37)

Comparison with Previous Version:
- The earlier version, UCSCXenaShiny v1.1.10 (utilizing UCSCXenaTools v1.4.8), does not exhibit this issue and functions as expected.
![image](https://github.com/openbiox/UCSCXenaShiny/assets/39810494/bc4a7480-c0d6-49f8-b8e0-cacc0171f483)
![image](https://github.com/openbiox/UCSCXenaShiny/assets/39810494/3fa24b46-d552-4554-a158-66022bc1eedb)

Could you please assist us in resolving this error? We suspect there might be a compatibility or data handling difference in the latest version affecting the handling of numeric data in expressions. Your guidance on this matter would be greatly appreciated.

Thank you for your attention to this issue.

Best regards,

Enrique

**Comment by ShixiangWang** [comment]
@quiquemedina Thanks for your report, as always. Yeah, this should be consistent, we will take a deep look at this and respond to you :)

**Comment by ShixiangWang** [comment]
@quiquemedina Hi, this bug should be fixed by @lishensuo , please install the latest version from GitHub and take it a try.

**Comment by lishensuo** [comment]
It is noteworthy that we have updated the interface of quick TPC modules, recently. 
![e259d3b6ef1a5fd38d6e21fd24cb51e](https://github.com/openbiox/UCSCXenaShiny/assets/80585985/7330ae35-d378-48c0-9619-b838306d74ce)

**Comment by quiquemedina** [comment]
Blast! Swiftly solved! Many thanks!

**Comment by ShixiangWang** [comment]
Good to hear that :).
