### ISSUE TITLE
Issues with Recent Update to QuickPanCan Analysis Functionalities

### ISSUE THREAD

**Issue by quiquemedina** [openbiox/UCSCXenaShiny#326]
Dear UCSC Xena Support Team,

I am writing to report some issues encountered following the recent update to the UCSC Xena platform. Notably, the entire QuickPanCan analysis module, previously located under "Custom TPC Modules," appears to be missing. As of yesterday, this section only included basic analysis tools and omitted specialized functionalities, such as the radar plots for stemness assessment.

Additionally, there seems to be a problem with the downloadable PDF files generated by the `tcga_surv_plot` function. Specifically, each document begins with an unnecessary blank page, resulting in files formatted as "1 of 2 pages" even though the actual content is only one page.

Could you please confirm whether these changes were intentional or if they stem from incomplete update processes? Your assistance in restoring the full functionality of the platform would be greatly appreciated.

Thank you for your attention to these matters.

Best regards,

Enrique

**Comment by ShixiangWang** [comment]
@quiquemedina 

Sorry for the inconvenience. @lishensuo Shensuo is actively developing the platform and reshaping the UI of the v2 version. For the stemness, you can refer to 

<img width="2463" alt="image" src="https://github.com/openbiox/UCSCXenaShiny/assets/25057508/5353f225-0dfd-43e1-b2b6-54dd7b2df25a">


For the survival plot pdf download, there's an issue with outputting the km plot generated by survminer package, we will take a quick fix.

**Comment by ShixiangWang** [comment]
@quiquemedina pdf issue should be addressed in the latest commit.

**Comment by ShixiangWang** [comment]
@quiquemedina Hi, do you have any feedback on this?

**Comment by quiquemedina** [comment]
@ShixiangWang, 

We are experiencing several issues with the v2 online portal browser and the Shiny app_run:

1. **Loading Delays** There is a significant delay when launching the UCSCXenaShiny v2.1.0, which is based on UCSCXenaTools v1.4.8, from either the web portal or the RStudio Shiny app. The portal is challenging to load and disconnects after a short period. Frequently, the browser becomes unresponsive and fails to open. I have tested this on multiple PCs and with various internet service providers, and the problem persists across all scenarios. Although our internet connection contributes partially to this issue, it remains consistent with other connections both within and outside the university.

2. **Navigational Challenges:** It is difficult to locate and understand the new placements of functionalities that have transitioned from the old to the new version. The changes are not intuitive for users familiar with the previous version. Even for features I specifically requested, locating them is challenging. A revised guide or tutorial could potentially make navigation smoother. However, the new features are beneficial for extracting secondary data and testing multiple hypotheses.

With the improvements in v2, the complexity of our analysis can be effectively tested. Nonetheless, the code examples must be provided for the new features in RStudio (e.g., Help section). Much of our analysis involves queries for multiple genes, and as such, we have developed programmatic querying based on the UCSCXena Shiny app.

**Comment by ShixiangWang** [comment]
@quiquemedina Thanks for your feedback, it's very important. We will improve the app based on the suggestions and make the app stable in a few months (RT to @lishensuo ).

**Comment by ShixiangWang** [comment]
Recently, we added app_run2() function for custom app start with lightweight modules.

https://openbiox.github.io/UCSCXenaShiny/reference/app_run2.html

**Comment by ShixiangWang** [comment]
We deployed two other apps, including basic version of V2 (https://shiny.zhoulab.ac.cn/UCSCXenaShiny_basic/) and the archive version of V1 (https://shiny.zhoulab.ac.cn/UCSCXenaShinyV1/).
