### ISSUE TITLE
GENE SIGNATURE FORMULA

### ISSUE THREAD

**Issue by Tardins** [openbiox/UCSCXenaShiny#331]
Greetings Dear developers!

I am having some problems using the "Multi-molecule formula" option in the Drug Reponse Association and Drug Reponse Difference analyses. I'm using a formula model that I've previously used in xenashiny analyzes (eg. (DUSP6 + `MT-ATP8` + SLC16A1)), but this formula doesn't seem to work anymore. The example model, shown on the platform, for the gene signature formula was not very clear. Is there a new way to build the formula for a genetic signature?

Regards,

Alan T.

**Comment by ShixiangWang** [comment]
@lishensuo

**Comment by lishensuo** [comment]
The above issue has been fixed. Please check if it meets your needs.  #332

**Comment by Tardins** [comment]
Greetings Dear developers!

I tried again to perform the "Drug Response Association and Drug Response Difference" analysis using the following signature as an example (`MT-ATP8` + H19 + IGF2 + ANK2). However, the signature didn't work, and I received the following warning: "Space is detected in your input, it's invalid"; I also received another warning: "This gene does not exist." However, when I try to analyze a single gene at a time, all of them are present within the database for this analysis, so I cannot understand what the problem could be, and I sincerely ask for your support, if possible. Thank you very much.

**Comment by lishensuo** [comment]
Got it. I will check the error later.



---- Replied Message ----
| From | ***@***.***> |
| Date | 07/02/2024 00:04 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [openbiox/UCSCXenaShiny] GENE SIGNATURE FORMULA (Issue #331) |

Greetings Dear developers!

I tried again to perform the "Drug Response Association and Drug Response Difference" analysis using the following signature as an example (MT-ATP8 + H19 + IGF2 + ANK2). However, the signature didn't work, and I received the following warning: "Space is detected in your input, it's invalid"; I also received another warning: "This gene does not exist." However, when I try to analyze a single gene at a time, all of them are present within the database for this analysis, so I cannot understand what the problem could be, and I sincerely ask for your support, if possible. Thank you very much.

**Comment by lishensuo** [comment]
1. We have updated all valid candidate genes for the input of drug analysis. (but not include genes, like MT-ATP8)
2. If users want to one gene signature, you can select multiple genes directly.
3. The tooltip can be appeared when hovering over the title '2. Select one gene list'.
![image](https://github.com/openbiox/UCSCXenaShiny/assets/80585985/0673c2ab-97ac-44c4-a1e5-f146c17a894b)

**Comment by Tardins** [comment]
Greetings Dear developers!

I apologize for the delay in returning, I was having health problems.

In my xenashiny interface, the option "select one gene list" does not appear. The options available for analysis are only: "One molecule" or "Multi-molecule formula". Within these options, I cannot insert the genes as a list, nor can I insert a formula whose program is accepted for my genetic set. Could it be that my xenashiny version is out of date?
![TESTE_XENASHINY](https://github.com/openbiox/UCSCXenaShiny/assets/96196930/2801493a-a979-4e62-83bf-1db74a9dcf9c)

**Comment by lishensuo** [comment]
You can visit the latest version by the following ways:
1. https://shiny.zhoulab.ac.cn/UCSCXenaShiny/ 
2. install R package `devtools::install_github("openbiox/UCSCXenaShiny")` and then run locally.
