### ISSUE TITLE
get_pancan_gene_value() failed

### ISSUE THREAD

**Issue by 234pk** [openbiox/UCSCXenaShiny#333]
get_pancan_gene_value("FOXO3") Try querying data #1 Try querying data #2 Try querying data #3 Try querying data #4 Try querying data #5 value[[3L]](cond)里有警告:   Tried 5 times but failed, please check URL or your internet connection or try it later! Saving data to file C:\Users\16500\AppData\Local\Temp\RtmpywyJuj/UCSCXenaShiny/08f944daca2796f2007b1fd22bbdb22c.rds More info about dataset please run following commands:   library(UCSCXenaTools)   XenaGenerate(subset = XenaDatasets == "TcgaTargetGtex_rsem_gene_tpm") %>% XenaBrowse() $expression NULL  $unit [1] "log2(tpm+0.001)"

 get_pcawg_gene_value("KRAS")
Try querying data #1
Try querying data #2
Try querying data #3
Try querying data #4
Try querying data #5
value[[3L]](cond)里有警告:
  Tried 5 times but failed, please check URL or your internet connection or try it later!
Saving data to file C:\Users\16500\AppData\Local\Temp\RtmpywyJuj/UCSCXenaShiny/00c1406cd3e8b2699869c1ae21952b93.rds
More info about dataset please run following commands:
  library(UCSCXenaTools)
  XenaGenerate(subset = XenaDatasets == "tophat_star_fpkm_uq.v2_aliquot_gl.sp.log") %>% XenaBrowse()
$data
NULL

$unit
[1] "log2(fpkm-uq+0.001)"

**Comment by lishensuo** [comment]
It could be due to your network. As you can see below, the test on my side is OK.
![image](https://github.com/openbiox/UCSCXenaShiny/assets/80585985/7fdf4c9a-cfb0-4dcc-bb12-dc44475bde20)

**Comment by ShixiangWang** [comment]
A typical networking issue
