### ISSUE TITLE
app_run2 模式下的资源加载问题

### ISSUE THREAD

**Issue by ShixiangWang** [openbiox/UCSCXenaShiny#341]
@lishensuo 

目前发现的是在 app_run2 的启动下 Quick_guide.pdf 无法访问，不知道是不是端口变更引起的，另外是否会有类似资源受到影响，需要调查下。

后续可以考虑把这种资源存在固定的地方。 目前这个 pdf 我已经改到腾讯云了。

https://ucscxenashiny-1301043367.cos.ap-shanghai.myqcloud.com/Quick_guide.pdf

https://github.com/openbiox/UCSCXenaShiny/commit/ea0b9bf3bd7c103358eaca66eb9fce994139d551

**Comment by ShixiangWang** [comment]
@lishensuo 后面你也要检查下 app_run2 的功能是否都稳定正常，关于这个函数的设计和开发我们可以highlight到文章和response里去的

**Comment by ShixiangWang** [comment]
> @lishensuo 后面你也要检查下 app_run2 的功能是否都稳定正常，关于这个函数的设计和开发我们可以highlight到文章和response里去的

关于 https://github.com/openbiox/UCSCXenaShiny/issues/326#issuecomment-2112978204 提到的问题和意见，我们在后续修回前能完善的也尽量完善。有什么问题及时沟通哈。

**Comment by lishensuo** [comment]
收到！

**Comment by ShixiangWang** [comment]
@lishensuo 这个 issue 和昨晚提到的你检查下有什么问题，然后针对 pdf 的访问，考虑到包内部也有一个稳定的存档，看是不是考虑优先访问腾讯云，在无法访问的情况下使用包内部的资源？下面的函数供你参考：

```r
url_pdf_accessible = function(url = "https://ucscxenashiny-1301043367.cos.ap-shanghai.myqcloud.com/Quick_guide.pdf") {
  tryCatch({
    headers <- curlGetHeaders(url)
    ct <- headers[grep("Content-Type", headers, ignore.case=TRUE)]
    grepl("pdf", ct)
  },
  error = function(x) FALSE)
}

url_pdf_accessible()
url_pdf_accessible("https://ucscxenashiny-1301043367.cos.ap-shanghai.myqcloud.com/Quick_guide")
url_pdf_accessible("abc")
```

以上基本解决后该 issue 可以关闭

**Comment by ShixiangWang** [comment]
<img width="152" alt="image" src="https://github.com/user-attachments/assets/33fbb8b4-5d42-4c79-874c-d5a7ef37723b">

这个是不work的，考虑直接加跳转链接到 https://shiny.zhoulab.ac.cn/UCSCXenaShiny/ ？

**Comment by lishensuo** [comment]
老师，原来设计app_run2()函数的目的也是为了分散部署shiny app。
这里的Advanced analysis下拉栏是想指向三个独立部署的子app（"q"-TPC modules, "p"-TPC pipelines, "d"-pharmcogenomics analysis，以最大化优化每个分析功能的加载时间。
![image](https://github.com/user-attachments/assets/d86c61dc-0cdf-4036-a3f5-d91bee5b7b4f)

**Comment by ShixiangWang** [comment]
这个策略我理解（包括目前basic也是这样部署的），但目前没有正常工作，如果别人访问basic的这个功能

**Comment by lishensuo** [comment]
嗯嗯，明白了老师。已修改相关代码，如下示意图。Whole Functionalities指向标准的V2版本；其它指向未来待部署的子App。
![image](https://github.com/user-attachments/assets/f94c33a7-772f-4fa1-b88c-61257b110a17)

**Comment by lishensuo** [comment]
> 嗯嗯，明白了老师。已修改相关代码，如下示意图。Whole Functionalities指向标准的V2版本；其它指向未来待部署的子App。 ![image](https://private-user-images.githubusercontent.com/80585985/352809503-f94c33a7-772f-4fa1-b88c-61257b110a17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNzMzMjksIm5iZiI6MTcyMjE3MzAyOSwicGF0aCI6Ii84MDU4NTk4NS8zNTI4MDk1MDMtZjk0YzMzYTctNzcyZi00ZmExLWI4OGMtNjEyNTdiMTEwYTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDEzMjM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyZDYwODFlMjk0MDAxM2E1OTIzNTUzYzk5MzljZTJkMDE1NDZkM2FhYjYyZDI5ZTk3ZGYyOTczN2U5OTVkMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hNEQlJHrdVMcovcsG3S8XZtEGQUrtz_Dgj9t9iiQSuE)

会在下次一并提交~
