### ISSUE TITLE
Why is the “mutation” genomic profile missing from the "Molecular Profile HR Cox analysis" module?

### ISSUE THREAD

**Issue by quiquemedina** [openbiox/UCSCXenaShiny#352]
Dear XenaShiny developers, 

I noticed that the “mutation” genomic profile is missing from the "Molecular Profile HR Cox analysis" module. 

Since the mutation profile is available in the log_rank survival analysis, I am unsure why the profile is missing from the selection options in the HR Cox analysis.
•	HR Cox analysis: The "mutation" profile option is absent.
•	log_rank survival analysis: The "mutation" profile option is present.

Specificaly: UCSCXenaShiny v1.1.8 based on UCSCXenaTools v1.4.8

In R manual,that data type also missing:
data_type: choose gene profile type, including "mRNA","transcript","methylation","miRNA","protein","cnv"

R Cox analysis: mutation ´profile option is absent
![image](https://github.com/user-attachments/assets/eaa01a8c-ea76-4d5f-ba7e-665351a32ed3)
 	
Log rank analysis: mutation ´profile option is present
![image](https://github.com/user-attachments/assets/dea19b7b-7e66-45ad-9743-dd96ded8a423)

**Comment by lishensuo** [comment]
Thanks for the suggestion.  We have added the 'mutation' profile for the Cox analysis of TCGA module in the latest update.

**Comment by lishensuo** [comment]
Thanks for your reminder. We will optimize it in the next commit.
