### ISSUE TITLE
`tcga_surv_get` function for methylation profiles is failing in R studio

### ISSUE THREAD

**Issue by quiquemedina** [openbiox/UCSCXenaShiny#359]
Dear developers, 

I noticed that the function tcga_surv_get for “methylation” profiles is failing in R Studio (UCSCXenaShiny versions 2.1.0 and 2.2.0) (see print screen 1), as well as in the new online app (https://shiny.hiplot.cn/ucsc-xena-shiny/).
The failure does not seem to be an issue with URL connectivity, as the function works fine in both the older UCSCXenaTools version 1.4.8 and the previous online app (https://shixiangwang.shinyapps.io/ucscxenashiny/).

Here is the code using UCSCXenaShiny versions 2.1.0 and 2.2.0:
r
Copiar código
library(UCSCXenaShiny)
library(UCSCXenaTools)
library(survminer)

data <- tcga_surv_get(
  item = "(PAX9 + SEMA4A)",
  TCGA_cohort = "LUAD",
  profile = "methylation",
  TCGA_cli_data = dplyr::full_join(load_data("tcga_clinical"), load_data("tcga_surv"), by = "sample"),
  opt_pancan = .opt_pancan
)

tcga_surv_plot(
  data,
  time = "DSS.time",
  status = "DSS",
  cutoff_mode = "Custom",
  cutpoint = c(50, 50),
  profile = "methylation",
  palette = "aaas"
)
Printscreen_1
 
![image](https://github.com/user-attachments/assets/bd23e48d-9a28-4c16-9d45-290e3360dcbe)

![image](https://github.com/user-attachments/assets/53fce551-23f1-453e-adc6-57579cdb4a71)

However, using UCSCXenaTools version 1.4.8, the function works fine (Printscreen_2)
r
Copiar código
library(UCSCXenaShiny)
library(UCSCXenaTools)
library(survminer)

data <- tcga_surv_get(
  item = "(PAX9 + SEMA4A)",
  TCGA_cohort = "LUAD",
  profile = "methylation",
  TCGA_cli_data = dplyr::full_join(load_data("tcga_clinical"), load_data("tcga_surv"), by = "sample")
)

tcga_surv_plot(
  data,
  time = "DSS.time",
  status = "DSS",
  cutoff_mode = "Custom",
  cutpoint = c(50, 50),
  profile = "methylation",
  palette = "aaas"
)

Printscreen_2

![image](https://github.com/user-attachments/assets/7d31f856-8f77-43dd-bbdd-72f745f0350a)
 
It seems that the code has not been updated for RStudio users after the UCSCXenaShiny versions 2.1.0 update.

Best regards,

Enrique

**Comment by ShixiangWang** [comment]
@lishensuo

**Comment by lishensuo** [comment]
Thank you for pointing out the issue. We've identified the cause of the bugs. The methylation datasets used in UCSCXenaShiny V2 were sourced from the GDC hub on the UCSC Xena platform:

- [GDC-PANCAN.methylation27.tsv](https://xenabrowser.net/datapages/?dataset=GDC-PANCAN.methylation27.tsv&host=https://gdc.xenahubs.net)
- [GDC-PANCAN.methylation450.tsv](https://xenabrowser.net/datapages/?dataset=GDC-PANCAN.methylation450.tsv&host=https://gdc.xenahubs.net)

Unfortunately, these datasets are currently inaccessible, which caused the error you encountered. We have now switched to alternative methylation datasets used in our V1 version. You should be able to run the methylation analysis successfully with the latest development version.

**Comment by quiquemedina** [comment]
Checked! 

Great, back in business! 

Many thanks!

**Comment by quiquemedina** [comment]
@lishensuo, you may be interested in the query reply I received from UCSC Xena regarding the issue, which I transcribe here for your reference

##########################
Hi Enrique,

We have recently updated the GDC data and retired the 2019 data you are referencing to another location: https://xenabrowser.net/datapages/?host=https%3A%2F%2FgdcV18.xenahubs.net&removeHub=https%3A%2F%2Fgdc.xenahubs.net. At this point in time we have not regenerated the GDC PanCan datasets on the new data from the GDC. 

Note that the 2019 GDC data will only be available for visualization until October 2025. After October 2025 it will only be available for download.

Please let me know if you have any questions.

Best,
Mary
-----
Mary Goldman (she/her), Design and Outreach Engineer

**Comment by lishensuo** [comment]
Thank you for sharing this information. To ensure stability, we are now using methylation datasets that are not sourced from the GDC hub. 
- [jhu-usc.edu_PANCAN_HumanMethylation450.betaValue_whitelisted.tsv](https://xenabrowser.net/datapages/?dataset=jhu-usc.edu_PANCAN_HumanMethylation450.betaValue_whitelisted.tsv.synapse_download_5096262.xena&host=https://pancanatlas.xenahubs.net)
- [TCGA.PANCAN.sampleMap/HumanMethylation27](https://xenabrowser.net/datapages/?dataset=TCGA.PANCAN.sampleMap/HumanMethylation27&host=https://tcga.xenahubs.net)

**Comment by ShixiangWang** [comment]
@quiquemedina I have recorded this, thanks for this info, I will update the old hub to UCSCXenaTools list
