### ISSUE TITLE
开发流程和工具链

### ISSUE THREAD

**Issue by ShixiangWang** [openbiox/UCSCXenaShiny#47]
根据 https://rtask.thinkr.fr/building-big-shiny-apps-a-workflow-2/ 文章的指引，我总结下我们协作开发的流程和使用的工具链

- [ ] 设计和构建原型: [shinipsum](https://github.com/ThinkR-open/shinipsum) 和 [fakir](https://github.com/ThinkR-open/fakir)
- [ ] 开发与构建: shiny、shinydashboard 和 [golem](https://github.com/ThinkR-open/golem)
- [ ] 测试：[testthat](https://github.com/r-lib/testthat) 与 [shinytest](https://github.com/rstudio/shinytest)
- [ ] 发布：以R包形式

**主要的工具是 shiny 和 golem 包，前者开发，后者辅助开发和测试**。

开发之前看下 https://thinkr-open.github.io/golem/articles/b_dev.html 了解下一些便利函数的用法，另外 golem 自动加了一些工具包，大家可以学习下提高开发效率

```
    processx,
    attempt,
    DT,
    glue,
    htmltools
```
另外还内置了一些工具函数在 R 目录下：

![image](https://user-images.githubusercontent.com/25057508/68068724-11132d00-fd93-11e9-8d6a-325800a04fba.png)

下面是 shiny 和 golem 的备查表，请大家有机会打印放到身边作为参考：

[cheatsheet.pdf](https://github.com/openbiox/XenaShiny/files/3800250/cheatsheet.pdf)
[golem_cheatsheet_v0.1.pdf](https://github.com/openbiox/XenaShiny/files/3800251/golem_cheatsheet_v0.1.pdf)

整体的 UI 布局我们暂时使用 Shiny Dashboard，文档见 <https://rstudio.github.io/shinydashboard/get_started.html>

**Comment by ShixiangWang** [comment]
容器构建：

- https://github.com/o2r-project/containerit/

**Comment by ShixiangWang** [comment]
刚偶然间看到一个工具：https://github.com/andrewsali/shinycssloaders

**Comment by ShixiangWang** [comment]
推荐用这个包渲染表格 https://github.com/glin/reactable @kaigu1990 刚看到

**Comment by kaigu1990** [comment]
@ShixiangWang shinycssloaders工具蛮实用的，我发现其github上有个直接用shiny下载代码库然后运行示例的方法蛮好的。如`shiny::runGitHub('andrewsali/shinycssloaders',subdir="example")`，我们可以试试

**Comment by kaigu1990** [comment]
@ShixiangWang reactable工具渲染表格的方式好多呀。。。得想想哪些可以拿来用用

**Comment by kaigu1990** [comment]
推荐一个shiny拓展包，用于读入文件（可多选文件、可选择指定文件夹，可用于创建文件夹），类似于windows上的页面；shinyFiles，[https://github.com/thomasp85/shinyFiles](https://github.com/thomasp85/shinyFiles)

**Comment by kaigu1990** [comment]
A cookbook for mastering shiny: [https://mastering-shiny.org/](https://mastering-shiny.org/)
里面有些建议蛮有意思的~

**Comment by kaigu1990** [comment]
Shiny Community在2019年初开办了一场shiny contest，如：[https://community.rstudio.com/t/take-part-in-the-shiny-contest/22445](https://community.rstudio.com/t/take-part-in-the-shiny-contest/22445)
其中优秀作品在再这里查看：[https://blog.rstudio.com/2019/04/05/first-shiny-contest-winners/](https://blog.rstudio.com/2019/04/05/first-shiny-contest-winners/)
所有作品可再Shiny Community中搜索“Shiny Contest Submission”，如：[https://community.rstudio.com/search?q=Shiny%20Contest%20Submission%3A%20category%3A8](https://community.rstudio.com/search?q=Shiny%20Contest%20Submission%3A%20category%3A8)

**Comment by ShixiangWang** [comment]
大家一起尽量把上次的分配任务完成哈，年后我会稳定推进开发的进行。这几天我补补 Shiny 😭

**Comment by ShixiangWang** [comment]
这个已经没用了。
