### ISSUE TITLE
Repository 的浏览和下载功能修改与优化

### ISSUE THREAD

**Issue by ShixiangWang** [openbiox/UCSCXenaShiny#71]

**Comment by ShixiangWang** [comment]
我之前看到的问题是如果选择一些数据集后再去掉选择就会出问题。

**Comment by ShixiangWang** [comment]
下载路径自定义也是一个问题。

**Comment by ShixiangWang** [comment]
![image](https://user-images.githubusercontent.com/25057508/84595347-ff961580-ae89-11ea-9710-965b525dcf60.png)

Load Data 无用 去掉。

第二个显示下载进度，并支持下载目录设定。

URL list 使用 wget -c

**Comment by ShixiangWang** [comment]
使用 Shinyfiles 包 https://github.com/thomasp85/shinyFiles 

server

```
library(shiny)
library(shinyFiles)

shinyServer(function(input, output, session) {

  # dir
  shinyDirChoose(input, 'dir', roots = c(home = '~'), filetypes = c('', 'txt'))
  dir <- reactive(input$dir)
  output$dir <- renderPrint(dir())

  # path
  path <- reactive({
    home <- normalizePath("~")
    file.path(home, paste(unlist(dir()$path[-1]), collapse = .Platform$file.sep))
  })

  # files
  output$files <- renderPrint(list.files(path()))
}) 
```
ui

```
library(shiny)
library(shinyFiles)

shinyUI(fluidPage(sidebarLayout(

  sidebarPanel(
    shinyDirButton("dir", "Chose directory", "Upload")
  ),

  mainPanel(
    h4("output$dir"),
    verbatimTextOutput("dir"), br(),
    h4("Files in that dir"),
    verbatimTextOutput("files")
  )

))) 

```

**Comment by ShixiangWang** [comment]
对数据集下载方式进行修改，由用户指定输出目录后，直接通过命令下载到对应目录下，另外输出整个下载的代码输出信息。

**Comment by Byronxy** [comment]
1 是否可以添加数据概览功能，比如在GDC数据库，我一开始想看到主要包含哪些数据，比如临床表型，基因表达数据

2 metadata 可否增加单位unit，数据预处理的过程wrangling,输入数据的格式input data format 

比较习惯看的时候metadata的特征放在行而不是列

3 This will check url status, please be patient.
这一步看能不能弹出窗口，而不是代码

4 这个tip要修改，一个是不易懂，另一个就是格式太混乱

**Comment by ShixiangWang** [comment]
第 1 点可以在 repository 中筛选查看到，单独实现比较困难。

第二点 unit 增加了，metadata 应该基本都放上去了吧，后续可以增加，本身能够获取的元数据还是蛮多的。

第 3 点这个输出是 UCSCXenatools 提供的，你可以试着加一些提示

**Comment by ShixiangWang** [comment]
```
Warning: Error in data.frame: arguments imply differing number of rows: 2, 0
  [No stack trace available]
```

有时候选择的变换会导致报错，这种问题原因和解决办法有吗？ @Byronxy

**Comment by ShixiangWang** [comment]
![image](https://user-images.githubusercontent.com/25057508/84789530-e5436f80-b022-11ea-93ea-7d73432bbc44.png)

左侧的选择栏可以在最外围加一个矩形框吗？ @Byronxy 

我尽量这周把下载的相关问题解决掉。

**Comment by ShixiangWang** [comment]
修改了下布局，但感觉使用类似 https://shiny.rstudio.com/gallery/update-input-demo.html 实现可能更好，明天试下。

**Comment by ShixiangWang** [comment]
@Byronxy title 与边框的距离有没有办法调小？

![image](https://user-images.githubusercontent.com/25057508/84916577-d2976c00-b0f0-11ea-877f-7dc31ba7c88f.png)

**Comment by ShixiangWang** [comment]
@kaigu1990 我们之前讨论的下载方式的改变有解决方案了吗？

**Comment by kaigu1990** [comment]
@ShixiangWang 我用shinyFiles包的`shinyDirButton`函数来指定输出目录，然后直接调用`UCSCXenaTools::XenaDownload`来下载文件，经测试是可行的，但是还无法将下载过程的产生的message发送到shiny的modal中

**Comment by ShixiangWang** [comment]
进度条暂时可以不用加，下载过程的信息能否使用代码输出框传输到shiny上？我记得有个 shiny::verbatimTextOutput()

**Comment by kaigu1990** [comment]
你的意思是下载的message是我们自己写？还是需要抓取download函数输出的message；如果是前者的话确实按照你说的方法就可以输出文本了，但是后者的话应该怎么实现呢

对于进度条，一种解决办法是不用`UCSCXenaTools::XenaDownload`，而采用`httr::GET`以及`shinyhttr::progress`，可参照：[https://www.rdocumentation.org/packages/shinyhttr/versions/1.0.0](https://www.rdocumentation.org/packages/shinyhttr/versions/1.0.0)

**Comment by ShixiangWang** [comment]
是不是可以使用 https://shiny.rstudio.com/reference/shiny/latest/renderPrint.html 来输出命令的输出到 Shiny?

如果你使用 GET 和 progress 组合实现了进度展示和数据下载也是可以的，那就不需要输出 download 运行信息了？

哪一种更好处理呢？

**Comment by kaigu1990** [comment]
我测试了下，还是无法抓取到download运行信息，可能还是建议会采用shinyhttr的方法

**Comment by ShixiangWang** [comment]
@kaigu1990 好，你试一试。XenaQuery 已经提供了链接地址，所以使用 GET 应该也还可以，后续需要注意下载数据的完整性检查之类的问题。

**Comment by ShixiangWang** [comment]
@Byronxy 你查一下最近的修改怎么导致 Home 和 Repository 页面都显示不正常了，我都没看懂为什么

**Comment by Byronxy** [comment]
> @Byronxy 你查一下你最近的代码修改怎么导致 Home 和 Repository 页面都显示不正常了，我都没看懂为什么

已经解决

**Comment by Byronxy** [comment]
我测试了一下，使用 devtools::load_all()之后，runApp，这个下载是可以指定路径的。但是重新安装包，然后使用app_run()，这个下载还是不行 @kaigu1990 @ShixiangWang

**Comment by ShixiangWang** [comment]
我重新克隆的仓库也没有办法看到指定下载

**Comment by ShixiangWang** [comment]
从commit 情况来看，顾凯还没有更新下载方面的修改呢~这个后面再讨论

**Comment by kaigu1990** [comment]
额，我看了下，是因为我添加的代码不在了，是我昨天没提交成功嘛？我再提交一次

**Comment by ShixiangWang** [comment]
应该是没有 commit 没有代码增删的记录啊

**Comment by ShixiangWang** [comment]
@kaigu1990 我使用浏览器用 Shiny 发现是看不到下载进度的，这样用户没办法判定下载已经完成，得想一个解决办法。

**Comment by kaigu1990** [comment]
@ShixiangWang 我用网页试了下，其实还是会有进度的，需要用户自己点开，我截图红色圈的部分；另外我尝试加个假进度条（即进度条变化不是实时的，而是等下载完成后直接从0到100%，可见蓝色圈的部分）
![image](https://user-images.githubusercontent.com/22772592/85116681-43a16580-b250-11ea-929e-433beed6c3f0.png)

**Comment by ShixiangWang** [comment]
@kaigu1990 好，暂时这样，主要是有一个明确的提示就会好很多了。

**Comment by kaigu1990** [comment]
我修改了repository，添加了progress and waiter；但是“有时候选择的变换会导致报错，这种问题原因和解决办法有吗”这个问题有时有，有时没。。。你们知道是哪方面的原因嘛

**Comment by ShixiangWang** [comment]
我再看看
