### ISSUE TITLE
单个基因转录分析

### ISSUE THREAD

**Issue by ShixiangWang** [openbiox/UCSCXenaShiny#72]
![image](https://user-images.githubusercontent.com/25057508/84594775-2272fa80-ae87-11ea-8f36-47abf9ec315f.png)

**Comment by ShixiangWang** [comment]
单基因转录组这个流程单独在 建 一个 pipeline 放到 pipeline 页面下吧~

**Comment by ShixiangWang** [comment]
@Byronxy 我们有一个 pipeline 页面，刚好你提到的流程大部分你都做过，你可以整合一个流程放到 pipeline 中。
![image](https://user-images.githubusercontent.com/25057508/84910714-ccea5800-b0e9-11ea-866a-119619a966b8.png)

**Comment by ShixiangWang** [comment]
试下企业微信机器人

**Comment by ShixiangWang** [comment]
再试下

**Comment by ShixiangWang** [comment]
@Byronxy 添加的数据需要写上文档，写到 https://github.com/openbiox/UCSCXenaShiny/blob/master/R/data.R，里面也有参考格式。

**Comment by Byronxy** [comment]
需要讨论一下每个图的可视化方式，和整理的排版@ShixiangWang

**Comment by ShixiangWang** [comment]
![image](https://user-images.githubusercontent.com/25057508/85088373-880e1080-b212-11ea-95d3-c89887ca5f81.png)

你自己新建一个个人命名的分支，建议删除这个 dev 分支

**Comment by ShixiangWang** [comment]
@Byronxy 一些建议：

模块是试验场，是独立的运作单元，建议分析流程中的几部分结果都构建为模块，像之前的 pancan 表达分布一样，构建好模块之后，然后有机地协调组成一个流程

1. 构建相关，Cox 分析模块
2. 本身的 UI 排布需要优化（每一部分分析也应该加标题），一些模块中的选项应该也要加入流程（如是否指定P值，颜色设置等一些主要的选项）
  
![image](https://user-images.githubusercontent.com/25057508/85096418-d9c09600-b226-11ea-9405-c6487315409f.png)

3. 流程中的数据获取需要优化，3个分析使用的应该是一样的表达数据吧？但重复向Xena服务器获取了3次，参考下面代码对数据进行缓存，同样的数据只获取一次，这样可以加速分析

https://github.com/openbiox/UCSCXenaShiny/blob/26d2a8c618af10ae48ca7772845dab0b994721d8/R/vis_pancan_value.R#L45-L58

4. 图片的分辨率是否能够设置？能否提供下载选项？

**Comment by ShixiangWang** [comment]
@Byronxy 我增加了两个空模块对应单基因的Cox和免疫相关分析，你有空添加下，尽量支持数据集的选择（也可以选择所有数据集），做好后再相应地优化流程。

![image](https://user-images.githubusercontent.com/25057508/85229095-667f7580-b41a-11ea-8e27-85f9d2e808a4.png)

**Comment by ShixiangWang** [comment]
/remind me to finish this feature in 2 weeks

**Comment by ShixiangWang** [comment]
云端 check 错误是无法安装到那个依赖包，它是psych包的依赖，挺奇怪的，暂时不管它

**Comment by ShixiangWang** [comment]
最近有 update 吗？

**Comment by ShixiangWang** [comment]
我想到针对 CCLE 这种细胞系数据也可以整单基因分析，有办法整合进去吗？ https://xenabrowser.net/datapages/?cohort=Cancer%20Cell%20Line%20Encyclopedia%20(CCLE)&removeHub=https%3A%2F%2Fxena.treehouse.gi.ucsc.edu%3A443

**Comment by Byronxy** [comment]
> 我想到针对 CCLE 这种细胞系数据也可以整单基因分析，有办法整合进去吗？ https://xenabrowser.net/datapages/?cohort=Cancer%20Cell%20Line%20Encyclopedia%20(CCLE)&removeHub=https%3A%2F%2Fxena.treehouse.gi.ucsc.edu%3A443

可以

**Comment by ShixiangWang** [comment]
@Byronxy 最近这个功能有更新吗？？

/remind me to get the updates of this feature in a week

**Comment by ShixiangWang** [comment]
@Byronxy 目前单基因流程你多久能优化好？？

另外我看到 这个解剖图建议把 性别选择放到基因选择框右侧，然后图形占满所有的列，目前看起来有点瘪

![image](https://user-images.githubusercontent.com/25057508/87879045-bbfb7200-ca1a-11ea-8b79-c0a8e81919c8.png)

**Comment by Byronxy** [comment]
> @Byronxy 目前单基因流程你多久能优化好？？
> 
> 另外我看到 这个解剖图建议把 性别选择放到基因选择框右侧，然后图形占满所有的列，目前看起来有点瘪
> 
> ![image](https://user-images.githubusercontent.com/25057508/87879045-bbfb7200-ca1a-11ea-8b79-c0a8e81919c8.png)

后面这几个module都要优化一下，我准备先等你们把这个下载问题解决了。图形优化应该不会花太长时间

**Comment by ShixiangWang** [comment]
@Byronxy 单个基因的数据下载我昨晚已经全部处理了。

**Comment by Byronxy** [comment]
近期准备增加双基因相关性绘制以及多组学热图功能

**Comment by ShixiangWang** [comment]
@Byronxy 

![image](https://user-images.githubusercontent.com/25057508/90203978-c724a080-de14-11ea-9bdd-400c258641ac.png)

Pipeline 这个图形排列感觉不行，你要不把那个方法的选择框放到最右下方？

下面 UI 文字差个空格也顺便改下吧。

![image](https://user-images.githubusercontent.com/25057508/90204556-f5a27b80-de14-11ea-9517-3fdb1fe42118.png)
