### ISSUE TITLE
泛癌免疫图谱数据

### ISSUE THREAD

**Issue by ShixiangWang** [openbiox/UCSCXenaShiny#75]
- 免疫细胞比例
- 肿瘤纯度
- 倍性

### 纯度

- https://www.nature.com/articles/ncomms9971 附加数据 https://static-content.springer.com/esm/art%3A10.1038%2Fncomms9971/MediaObjects/41467_2015_BFncomms9971_MOESM1236_ESM.xlsx

### 免疫浸润

- https://www.cell.com/immunity/fulltext/S1074-7613(18)30121-3#secsectitle0095 table S1

### 综述

- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6006237/

**Comment by ShixiangWang** [comment]
@Byronxy 上面是我目前收集的一些内容，你可以把你找到的做一个整合，选择比较合适和一致的数据加到你的 pipeline 中去展示分析和可视化。

**Comment by Byronxy** [comment]
目前主要的一些数据都已经加入了

**Comment by ShixiangWang** [comment]
好 我抽空check下 写一下文档
