### ISSUE TITLE
生存分析优化

### ISSUE THREAD

**Issue by ShixiangWang** [openbiox/UCSCXenaShiny#91]
生分分析模块是之前龙飞做的，做的蛮好的，我现在有一些优化的想法

![image](https://user-images.githubusercontent.com/25057508/85593941-11da3580-b67a-11ea-89a6-41acb58fc157.png)

1. 目前的代码是每次分析下载生存分析数据，而目前包里面已经有TCGA全部的生存数据，所以这个数据需要替换，加速分析
2. 生存分析可以从不同的层面，比如基因表达、突变、CNV等，目前仅支持表达，需要做一个拓展 ，根据 TCGA hub 提供的 cohort 结构，如 https://xenabrowser.net/datapages/?cohort=TCGA%20Head%20and%20Neck%20Cancer%20(HNSC)&removeHub=https%3A%2F%2Fxena.treehouse.gi.ucsc.edu%3A443，我觉得接下来可以增加基因水平上的突变、GISTIC2、Protein表达用户分组进行生存分析
3. 生存分析绘图需要优化，并支持下载 png,pdf结果。

目前 repository 修改已经完成，顾凯@kaigu1990 你是否感兴趣做下这些内容？我从旁协助。

对了，我感觉图形输出支持 png和pdf下载是一个常用的操作，能否做出一个单独的模块？

**Comment by ShixiangWang** [comment]
/remind me to finish this feature in a week

**Comment by ShixiangWang** [comment]
@kaigu1990 有空看下吗？

**Comment by kaigu1990** [comment]
@ShixiangWang  不好意思，之前没看到这条信息。。我晚上看下这个模块

**Comment by kaigu1990** [comment]
对于生存数据，我们是数据是不是存储在`data/toil_surv.rda`？但是里面有个患者ID，并没有对应到某个数据集，那么我们需不需要在重新制作下这个数据集呢？还是说我们在app里用程序来自动找到对应关系
另外我打算先以现有的为模块，做个类似的基因突变模块，大家有什么建议的么？是单纯以单突变与否来作为切点么？还是多基因突变？还是还有其他方法，我因为好久没看这方面的资料了哈~
对于下载png/pdf这个，我觉得可以写成一个模块方便调用

**Comment by ShixiangWang** [comment]
有患者id就可以映射，目前支持生存分析的都是tcga的数据 如果你后续想加入对xena 全部含生存数据的数据集分析，可以把信息加入这个数据中 另外这个数据可以使用 data 函数调用

**Comment by Byronxy** [comment]
> 对于生存数据，我们是数据是不是存储在`data/toil_surv.rda`？但是里面有个患者ID，并没有对应到某个数据集，那么我们需不需要在重新制作下这个数据集呢？还是说我们在app里用程序来自动找到对应关系
> 另外我打算先以现有的为模块，做个类似的基因突变模块，大家有什么建议的么？是单纯以单突变与否来作为切点么？还是多基因突变？还是还有其他方法，我因为好久没看这方面的资料了哈~
> 对于下载png/pdf这个，我觉得可以写成一个模块方便调用

突变和CNV的做法可以参考cbioportal

**Comment by kaigu1990** [comment]
我看下生存分析模块的代码，我发现原来是通过下载clinical matrix和survival data来做生存分析的，但是我们现在只有已下载好的survival data，而clinical matrix还是需要下载的，这样似乎还是避免不了下载文件的步骤欸，大家有说明看法嘛！@Byronxy，@ShixiangWang

**Comment by ShixiangWang** [comment]
要么统一整理存放临床数据，但很多指标都加的话包就越来越大了

**Comment by kaigu1990** [comment]
要么先加个别几个指标，这样可以重复利用，因为基因突变/拷贝数突变等都能用到同一个临床数据

**Comment by ShixiangWang** [comment]
@kaigu1990  更新 toil_surv 为 https://www.cell.com/cell/fulltext/S0092-8674(18)30229-0?utm_campaign=STMJ_1522958526_SC&utm_channel=WEB&utm_source=WEB&dgcid=STMJ_1522958526_SC#supplementaryMaterial 这篇文章提供的数据，看下面 Excel 的表格 1

[mmc1.xlsx](https://github.com/openbiox/UCSCXenaShiny/files/4882166/mmc1.xlsx)

目前 toil_surv 提供的几种生存信息就是来源于这篇文章

**Comment by ShixiangWang** [comment]
@kaigu1990 你清理下这个表格替换掉原有的 toil_surv。  如果后续我们想纳入 Xena 非 TCGA 一些数据集信息，再慢慢更新吧

**Comment by kaigu1990** [comment]
@ShixiangWang 对于TCGA数据，原来的方式中会通过这种`sample_type == names(which.max(table(sample_type)))`方法来过滤掉非tumor的样本的临床数据

**Comment by kaigu1990** [comment]
我尝试了下，对于是否将png/pdf下载写成module这个问题，我觉得还是不用module形式吧，因为可能不同分析模块下对于这个下载功能布局排版可能会不一样

---
另外在生存分析模块中，表达谱的数据是通过`UCSCXenaTools::fetch_dense_values`方法来获取的，那么基因突变/CNV/蛋白表达等数据也是类似的方法嘛？

---
还有对于我们这个包，还能再加一些依赖包嘛？比如shinydashboard/shinydashboardPlus等，假如我想加box的话

**Comment by ShixiangWang** [comment]
应该可以的，你先写好Ui，我这两天有空写一下怎么获取其他数据。

关于依赖，你觉得有用有价值都可以先加上

**Comment by ShixiangWang** [comment]
@kaigu1990 

请查看 `?get_pancan_value` 如何获取蛋白表达和基因突变的数据

支持的蛋白不是很多，我把列表存为包的一个隐藏变量，载入 XenaShiny 后可以直接调用。

![image](https://user-images.githubusercontent.com/25057508/87250199-dfac3e80-c495-11ea-928a-caabe793fcd9.png)

**Comment by ShixiangWang** [comment]
@kaigu1990 目前生存分析模型 UI 蛮好的。我看到有一些小问题，一个是突变是不支持 cutoff mode 的，因为它只有突变和不突变两种可能。另外就是生存分析图分组标签，建议统一改成High和Low，然后如果是突变就改成MT和WT

目前还不能访问 拷贝数数据吧？

**Comment by ShixiangWang** [comment]
@kaigu1990 目前生存分析模型 UI 蛮好的。我看到有一些小问题，一个是突变是不支持 cutoff mode 的，因为它只有突变和不突变两种可能。另外就是生存分析图分组标签，建议统一改成High和Low，然后如果是突变就改成MT和WT

目前还不能访问 拷贝数数据吧？

**Comment by ShixiangWang** [comment]
@kaigu1990 @Byronxy `cliMat` 这个数据是谁加的呢？有空加下文档哈

```
> checking for missing documentation entries ... WARNING
  Undocumented code objects:
    ‘cliMat’
  Undocumented data sets:
    ‘cliMat’
```

**Comment by kaigu1990** [comment]
@ShixiangWang 好的，ok

**Comment by ShixiangWang** [comment]
@kaigu1990 目前基因水平（Pancan和CCLE）的CNV、基因表达、蛋白表达、突变信息获取函数全部都有了，你抽空把目前生存分析的功能进行实现和拓展哈 @longfei8533 龙飞你之前在这里有很多贡献，如果有空也可以一起处理下。

https://github.com/openbiox/UCSCXenaShiny/blob/05237e6e7f4ec292911e9b6e1ced9f4781b6a2ac/R/get_pancan_value.R#L113-L238

https://github.com/openbiox/UCSCXenaShiny/blob/05237e6e7f4ec292911e9b6e1ced9f4781b6a2ac/R/ccle.R#L3-L145

**Comment by longfei8533** [comment]
> @kaigu1990 目前基因水平（Pancan和CCLE）的CNV、基因表达、蛋白表达、突变信息获取函数全部都有了，你抽空把目前生存分析的功能进行实现和拓展哈 @longfei8533 龙飞你之前在这里有很多贡献，如果有空也可以一起处理下。
> 
> https://github.com/openbiox/UCSCXenaShiny/blob/05237e6e7f4ec292911e9b6e1ced9f4781b6a2ac/R/get_pancan_value.R#L113-L238
> 
> https://github.com/openbiox/UCSCXenaShiny/blob/05237e6e7f4ec292911e9b6e1ced9f4781b6a2ac/R/ccle.R#L3-L145

嗯嗯 好的 我看下

**Comment by ShixiangWang** [comment]
- [ ] CNV 支持待增加
- [ ] CCLE 数据集支持待增加

我发现 LUAD KRAS 高低表达的生存差异与我之前的 post https://shixiangwang.github.io/home/en/post/ucscxenatools-201908/ 相去甚远，这是数据问题还是代码问题？ @longfei8533 你有空 check 下？

![image](https://user-images.githubusercontent.com/25057508/88629793-4a8a8600-d0e2-11ea-9d02-d2bab682fb63.png)

**Comment by longfei8533** [comment]
> * [ ]  CNV 支持待增加
> * [ ]  CCLE 数据集支持待增加
> 
> 我发现 LUAD KRAS 高低表达的生存差异与我之前的 post https://shixiangwang.github.io/home/en/post/ucscxenatools-201908/ 相去甚远，这是数据问题还是代码问题？ @longfei8533 你有空 check 下？
> 
> ![image](https://user-images.githubusercontent.com/25057508/88629793-4a8a8600-d0e2-11ea-9d02-d2bab682fb63.png)

![image](https://user-images.githubusercontent.com/37660840/88755304-7154c500-d193-11ea-9eb8-01b33e386a81.png)
额 以前的没有问题呀，这是修改后出了问题是吧？

**Comment by longfei8533** [comment]
> * [ ]  CNV 支持待增加
> * [ ]  CCLE 数据集支持待增加
> 
> 我发现 LUAD KRAS 高低表达的生存差异与我之前的 post https://shixiangwang.github.io/home/en/post/ucscxenatools-201908/ 相去甚远，这是数据问题还是代码问题？ @longfei8533 你有空 check 下？
> 
> ![image](https://user-images.githubusercontent.com/25057508/88629793-4a8a8600-d0e2-11ea-9d02-d2bab682fb63.png)

正在检查修改

**Comment by ShixiangWang** [comment]
@kaigu1990 下面这两个完成了吗？ 
CNV 支持待增加
 CCLE 数据集支持待增加

前两天增加了甲基化数据获取方式，这个也可以增加喔 

@yinlisssss 甲基化数据值一般怎么分组的？

这些完成了的喔，这个issue就可以正式关闭了。

**Comment by ShixiangWang** [comment]
@kaigu1990 

![image](https://user-images.githubusercontent.com/25057508/90203775-38178880-de14-11ea-968c-791205adb6d7.png)

Duplicated 改成 Amp或AMP，Deleted 改成 Del 或 DEL

甲基化有空也加一下？按照 mRNA 的逻辑添加个选项即可。
