### ISSUE TITLE
添加表达量解剖图展示

### ISSUE THREAD

**Issue by Byronxy** [openbiox/UCSCXenaShiny#97]
理想情况
![image](https://user-images.githubusercontent.com/28949856/86534581-fbe73300-bf0b-11ea-9fd2-b188c881e080.png)
可行情况，目前在实现，用gganatogram包
![image](https://user-images.githubusercontent.com/28949856/86534594-128d8a00-bf0c-11ea-8cba-df682125dfc7.png)
@ShixiangWang

**Comment by ShixiangWang** [comment]
挺好的 你这是添加单基因在不同组织中的表达？

**Comment by Byronxy** [comment]
> 挺好的 你这是添加单基因在不同组织中的表达？

已经完成了gganatogram实现的模块

**Comment by ShixiangWang** [comment]
@Byronxy 我改了下你的这个函数代码，但没有修改逻辑，奇怪的是 group_by 后汇总会报错，你有空仔细检查下问题。

**Comment by Byronxy** [comment]
> @Byronxy 我改了下你的这个函数代码，但没有修改逻辑，奇怪的是 group_by 后汇总会报错，你有空仔细检查下问题。

你的报错是哪个地方。我看了下出图是没问题的
![image](https://user-images.githubusercontent.com/28949856/86544980-d71bab80-bf5d-11ea-8380-2e618973ce27.png)

**Comment by Byronxy** [comment]
![image](https://user-images.githubusercontent.com/28949856/86545776-9757c280-bf63-11ea-9589-7d13ce098b82.png)
@ShixiangWang 我直接运行也没问题

**Comment by ShixiangWang** [comment]
@Byronxy 我刚用另一个电脑还是有问题， 我检查了下代码修改了下。

目前看到一个界面上的问题是

![image](https://user-images.githubusercontent.com/25057508/86550108-1ce36e80-bf74-11ea-82e2-ef0841b7e9d3.png)

你需要修改下当没有电搜索按钮时不要进行数据的查询。

**Comment by ShixiangWang** [comment]
目前这个功能应该算完成了，我先关掉了。
